/* Data Detective: the three fictional profiles from 3-5 Reproducibles R-5.1 (cards numbered as in the guide).
   All kids and places are invented. "clues" are the kinds of fact a card gives away. "safe" is a safer rewrite (R-5.2 style). */
window.HK_DATA = window.HK_DATA || {};
window.HK_DATA.detective = {
  categories: ["name", "age", "school", "home", "schedule", "password"],
  kids: [
    { id: "jordan", name: "Jordan", cards: [
      { n: 2,  clues: ["school"],
        en: "Maple Hill Elementary, 4th grade, Ms. Gray's class. We are the best class!",
        es: "Maple Hill Elementary, cuarto grado, la clase de la Sra. Gray. ¡Somos la mejor clase!",
        safe: { en: "We are the best class!", es: "¡Somos la mejor clase!" } },
      { n: 8,  clues: ["home"],
        en: "My new bike! [Picture: a kid with a bike in front of a blue house with the number 40 on the door and a street sign reading Willow Lane.]",
        es: "¡Mi bici nueva! [Imagen: un niño con una bici frente a una casa azul con el número 40 en la puerta y un letrero de calle que dice Willow Lane.]",
        safe: { en: "Look at my new bike! (Cropped photo with no door number and no street sign.)", es: "¡Miren mi bici nueva! (Foto recortada, sin número de puerta y sin letrero de calle.)" } },
      { n: 10, clues: ["password"],
        en: "Guess my password? Hint: it's my dog's name and the year I was born!",
        es: "¿Adivinan mi contraseña? Pista: ¡es el nombre de mi perro y el año en que nací!",
        safe: null },
      { n: 13, clues: ["name", "school"],
        en: "Maple Hill Mustangs win again! The team page says: #12 Jordan Pell scored twice. [Picture: a kid in a Mustangs jersey.]",
        es: "¡Los Maple Hill Mustangs ganan otra vez! La página del equipo dice: #12 Jordan Pell anotó dos veces. [Imagen: un niño con la camiseta de los Mustangs.]",
        safe: { en: "We won again! Go team!", es: "¡Ganamos otra vez! ¡Arriba el equipo!" } },
      { n: 14, clues: ["age", "password"],
        en: "JoJo_Goals12 here! I'm 9 and I love soccer and my dog Biscuit!",
        es: "¡Aquí JoJo_Goals12! Tengo 9 años y me encanta el fútbol y mi perro Biscuit.",
        safe: { en: "Hi! I love soccer.", es: "¡Hola! Me encanta el fútbol." } },
      { n: 17, clues: ["schedule"],
        en: "Bus 14 drops me off at 3:45! Soccer practice is Wednesdays at 4:30 at the Maple field.",
        es: "¡El autobús 14 me deja a las 3:45! El entrenamiento de fútbol es los miércoles a las 4:30 en el campo Maple.",
        safe: { en: "Excited for practice this week!", es: "¡Con ganas del entrenamiento esta semana!" } }
    ] },
    { id: "mina", name: "Mina", cards: [
      { n: 3,  clues: ["schedule"],
        en: "Violin lesson Thursday at 4 at Harbor Music Hall. Mom picks me up at 6.",
        es: "Clase de violín el jueves a las 4 en Harbor Music Hall. Mamá me recoge a las 6.",
        safe: { en: "Love music class!", es: "¡Me encanta la clase de música!" } },
      { n: 5,  clues: ["school"],
        en: "Cedar Ridge Elementary orchestra rocks! [Picture: kids in matching orchestra shirts.]",
        es: "¡La orquesta de Cedar Ridge Elementary es genial! [Imagen: niños con camisetas iguales de la orquesta.]",
        safe: { en: "Orchestra rocks!", es: "¡La orquesta es genial!" } },
      { n: 6,  clues: ["name", "age"],
        en: "Hi! I'm Mina, I'm 10, and I play the violin.",
        es: "¡Hola! Soy Mina, tengo 10 años y toco el violín.",
        safe: { en: "Hi! I play the violin.", es: "¡Hola! Toco el violín." } },
      { n: 7,  clues: ["name"],
        en: "New violin case! [Picture: a case with a sticker that reads MINA CHEN-ORTIZ.]",
        es: "¡Estuche nuevo de violín! [Imagen: un estuche con una calcomanía que dice MINA CHEN-ORTIZ.]",
        safe: { en: "New violin case! (The name sticker is covered.)", es: "¡Estuche nuevo de violín! (La calcomanía con el nombre está tapada.)" } },
      { n: 12, clues: ["home"],
        en: "Our apartment is above Rosa's Bakery on Pine Street. The smell is amazing every morning.",
        es: "Nuestro apartamento está encima de la Panadería de Rosa en la calle Pine. El olor es increíble cada mañana.",
        safe: { en: "Good smells in the morning!", es: "¡Qué buenos olores por la mañana!" } },
      { n: 18, clues: ["password"],
        en: "My cat Noodle hid my bow again! Noodle is the best cat ever.",
        es: "¡Mi gata Noodle escondió mi arco otra vez! Noodle es la mejor gata del mundo.",
        safe: { en: "My cat hid my bow again!", es: "¡Mi gata escondió mi arco otra vez!" } }
    ] },
    { id: "eli", name: "Eli", cards: [
      { n: 1,  clues: ["home", "password"],
        en: "Come see my frog Hopper at Oak Court, number 7, the house with the red mailbox!",
        es: "¡Vengan a ver a mi rana Hopper en Oak Court, número 7, la casa con el buzón rojo!",
        safe: { en: "My frog is so cool!", es: "¡Mi rana es genial!" } },
      { n: 4,  clues: ["password"],
        en: "My password is Hopper8, lol. Don't tell anyone.",
        es: "Mi contraseña es Hopper8, jaja. No se lo digan a nadie.",
        safe: null },
      { n: 9,  clues: ["school"],
        en: "Riverbend Elementary found a frog in the school pond today!",
        es: "¡Hoy Riverbend Elementary encontró una rana en el estanque de la escuela!",
        safe: { en: "We found a frog in the pond today!", es: "¡Hoy encontramos una rana en el estanque!" } },
      { n: 11, clues: ["schedule"],
        en: "I get home at 3:30 and my dad works until 6.",
        es: "Llego a casa a las 3:30 y mi papá trabaja hasta las 6.",
        safe: { en: "Looking forward to after school!", es: "¡Con ganas de la salida de la escuela!" } },
      { n: 15, clues: ["school", "name"],
        en: "Me in my Riverbend Rockets shirt! [Picture: a kid with a backpack with the name ELI NAVARRO on it.]",
        es: "¡Yo con mi camiseta de los Riverbend Rockets! [Imagen: un niño con una mochila con el nombre ELI NAVARRO.]",
        safe: { en: "Me in my team shirt! (The name on the backpack is covered.)", es: "¡Yo con la camiseta de mi equipo! (El nombre de la mochila está tapado.)" } },
      { n: 16, clues: ["name", "age"],
        en: "Eli here, age 8, and I love frogs!",
        es: "Aquí Eli, tengo 8 años, ¡y me encantan las ranas!",
        safe: { en: "Hi, I love frogs!", es: "¡Hola, me encantan las ranas!" } }
    ] }
  ]
};
