/* Data Detective: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "detective.title": "Data Detective",
    "detective.kicker": "Plate 4 of 6",
    "detective.lead": "One clue is harmless. Many small clues together can show who someone is and where to find them. You will see how, then decide what you would change.",
    "detective.frame": "We are Data PROTECTORS. These kids are made up and nobody is looking for a real kid. We look at what a stranger could see so we know what to fix. Any match to a real person or place is a coincidence.",
    "detective.noinput": "There is nothing to type on this page. Never type real names, schools or addresses into any website because a game or quiz asks you to.",
    "detective.choose": "Pick a made-up kid to look at",
    "detective.kid": "{name}'s posts",
    "detective.start": "Start with {name}",
    "detective.posts": "Posts you can see",
    "detective.reveal": "Show the next post",
    "detective.postN": "Post {n} of {total}",
    "detective.board": "What a stranger could work out",
    "detective.cat.name": "Name",
    "detective.cat.age": "Age",
    "detective.cat.school": "School",
    "detective.cat.home": "Where they live",
    "detective.cat.schedule": "Where they are and when",
    "detective.cat.password": "A password guess",
    "detective.yes": "known",
    "detective.no": "not yet",
    "detective.lvl.crumb": "So far this is just a crumb. Each fact alone is harmless.",
    "detective.lvl.who": "Now a stranger could tell who this kid is. Still no map.",
    "detective.lvl.home": "Now a stranger could find where this kid lives.",
    "detective.lvl.trail": "Now the clues are a map: where this kid lives, and where they are and when. Each post was harmless alone. Together they are a trail.",
    "detective.predict": "Could a stranger find this kid yet?",
    "detective.p.yes": "I think yes",
    "detective.p.no": "I think not yet",
    "detective.p.unsure": "I am not sure",
    "detective.p.thanks": "Good noticing. Let's keep looking.",
    "detective.seeAll": "I have seen every post. Show the case file",
    "detective.file": "The case file",
    "detective.fileSub": "No single post gave the whole picture. You pieced it together. That is a data trail.",
    "detective.fileHow": "It took {n} posts to work out where {name} lives.",
    "detective.fileHowNone": "These posts never gave away where {name} lives, but they gave away other clues.",
    "detective.th.fact": "Fact",
    "detective.th.found": "Found in post",
    "detective.notFound": "not found",
    "detective.postNum": "post {n}",
    "detective.pw": "A pet name plus a year, or a password posted in the open, is a gift to a guesser. Passwords are only for you and a trusted adult.",
    "detective.toReflect": "What would you change?",
    "detective.reflect": "What would you change?",
    "detective.reflectSub": "For each post, choose what you would do. Then see whether the clues still add up.",
    "detective.d.keep": "Keep it",
    "detective.d.change": "Change it",
    "detective.d.remove": "Remove it",
    "detective.safeIs": "A safer version: {t}",
    "detective.noSafe": "Never share password clues. Delete this one.",
    "detective.removed": "Removed.",
    "detective.after": "After your changes",
    "detective.after.none": "The clues no longer add up. Nice work, Data Protector.",
    "detective.after.some": "A stranger could still work out: {t}.",
    "detective.after.still": "Some posts are still giving clues. Try changing one more.",
    "detective.clueCheck": "The Clue Check",
    "detective.cc1": "Does this post show a full name, school, address, or where I will be and when? If yes, pause and change it or skip it.",
    "detective.cc2": "Could someone put three of my posts together and find me? If yes, pause and ask a grown-up.",
    "detective.cc3": "Who can see this: only my family, my friends, or anyone? Check the settings with a grown-up.",
    "detective.cc4": "Is it a picture with my house number, a street sign, my school shirt or my name? If yes, ask a grown-up first.",
    "detective.keep": "We do not stop sharing everything. We choose carefully. If you ever shared something and wish you had not, tell a trusted adult. It is never your fault and you can fix it together.",
    "detective.plan": "Pick the habit you will try first",
    "detective.plan.1": "Crop out door numbers and street signs",
    "detective.plan.2": "Cover names on backpacks and shirts",
    "detective.plan.3": "Never post when and where I will be",
    "detective.plan.4": "Check privacy settings with a grown-up",
    "detective.plan.picked": "Your habit: {t}",
    "detective.another": "Look at another kid",
    "detective.lab": "Back to Lab home",
    "detective.live.reveal": "Post {n} shown. {lvl}",
    "detective.live.file": "Case file shown."
  },
  es: {
    "detective.title": "Detective de Datos",
    "detective.kicker": "Lámina 4 de 6",
    "detective.lead": "Una pista sola es inofensiva. Muchas pistas pequeñas juntas pueden mostrar quién es alguien y dónde encontrarlo. Verás cómo, y luego decidirás qué cambiarías.",
    "detective.frame": "Somos PROTECTORES de datos. Estos niños son inventados y nadie busca a un niño de verdad. Miramos lo que un desconocido podría ver para saber qué arreglar. Cualquier parecido con una persona o un lugar real es casualidad.",
    "detective.noinput": "En esta página no hay nada que escribir. Nunca escribas nombres, escuelas ni direcciones reales en ningún sitio porque un juego o un cuestionario lo pida.",
    "detective.choose": "Elige un niño inventado para mirar",
    "detective.kid": "Las publicaciones de {name}",
    "detective.start": "Empezar con {name}",
    "detective.posts": "Publicaciones que puedes ver",
    "detective.reveal": "Mostrar la siguiente publicación",
    "detective.postN": "Publicación {n} de {total}",
    "detective.board": "Lo que un desconocido podría deducir",
    "detective.cat.name": "Nombre",
    "detective.cat.age": "Edad",
    "detective.cat.school": "Escuela",
    "detective.cat.home": "Dónde vive",
    "detective.cat.schedule": "Dónde está y cuándo",
    "detective.cat.password": "Una pista para adivinar la contraseña",
    "detective.yes": "se sabe",
    "detective.no": "todavía no",
    "detective.lvl.crumb": "Hasta ahora solo es una miga. Cada dato solo es inofensivo.",
    "detective.lvl.who": "Ahora un desconocido podría saber quién es este niño. Todavía no hay mapa.",
    "detective.lvl.home": "Ahora un desconocido podría encontrar dónde vive este niño.",
    "detective.lvl.trail": "Ahora las pistas son un mapa: dónde vive este niño, y dónde está y cuándo. Cada publicación era inofensiva sola. Juntas son un rastro.",
    "detective.predict": "¿Podría un desconocido encontrar a este niño ya?",
    "detective.p.yes": "Creo que sí",
    "detective.p.no": "Creo que todavía no",
    "detective.p.unsure": "No estoy seguro",
    "detective.p.thanks": "Buen ojo. Sigamos mirando.",
    "detective.seeAll": "Ya vi todas las publicaciones. Mostrar el expediente",
    "detective.file": "El expediente",
    "detective.fileSub": "Ninguna publicación mostró todo el panorama. Tú lo armaste. Eso es un rastro de datos.",
    "detective.fileHow": "Hicieron falta {n} publicaciones para saber dónde vive {name}.",
    "detective.fileHowNone": "Estas publicaciones nunca revelaron dónde vive {name}, pero revelaron otras pistas.",
    "detective.th.fact": "Dato",
    "detective.th.found": "Se encontró en",
    "detective.notFound": "no se encontró",
    "detective.postNum": "publicación {n}",
    "detective.pw": "El nombre de una mascota más un año, o una contraseña publicada a la vista, es un regalo para quien adivina. Las contraseñas son solo para ti y un adulto de confianza.",
    "detective.toReflect": "¿Qué cambiarías?",
    "detective.reflect": "¿Qué cambiarías?",
    "detective.reflectSub": "Para cada publicación, elige qué harías. Luego mira si las pistas todavía suman.",
    "detective.d.keep": "Dejarla",
    "detective.d.change": "Cambiarla",
    "detective.d.remove": "Quitarla",
    "detective.safeIs": "Una versión más segura: {t}",
    "detective.noSafe": "Nunca compartas pistas de contraseñas. Borra esta.",
    "detective.removed": "Quitada.",
    "detective.after": "Después de tus cambios",
    "detective.after.none": "Las pistas ya no suman. Buen trabajo, Protector de datos.",
    "detective.after.some": "Un desconocido todavía podría deducir: {t}.",
    "detective.after.still": "Algunas publicaciones todavía dan pistas. Prueba a cambiar una más.",
    "detective.clueCheck": "La Revisión de Pistas",
    "detective.cc1": "¿Esta publicación muestra un nombre completo, la escuela, la dirección o dónde estaré y cuándo? Si es así, haz pausa y cámbiala o sáltala.",
    "detective.cc2": "¿Podría alguien juntar tres de mis publicaciones y encontrarme? Si es así, haz pausa y pregúntale a un adulto.",
    "detective.cc3": "¿Quién puede ver esto: solo mi familia, mis amigos o cualquiera? Revisa la configuración con un adulto.",
    "detective.cc4": "¿Es una imagen con el número de mi casa, un letrero de calle, la camiseta de mi escuela o mi nombre? Si es así, pregúntale primero a un adulto.",
    "detective.keep": "No dejamos de compartir todo. Elegimos con cuidado. Si alguna vez compartiste algo y desearías no haberlo hecho, cuéntaselo a un adulto de confianza. Nunca es tu culpa y pueden arreglarlo juntos.",
    "detective.plan": "Elige el hábito que probarás primero",
    "detective.plan.1": "Recortar números de puerta y letreros de calle",
    "detective.plan.2": "Tapar nombres en mochilas y camisetas",
    "detective.plan.3": "No publicar cuándo y dónde estaré",
    "detective.plan.4": "Revisar la configuración de privacidad con un adulto",
    "detective.plan.picked": "Tu hábito: {t}",
    "detective.another": "Mirar a otro niño",
    "detective.lab": "Volver al inicio del Laboratorio",
    "detective.live.reveal": "Se mostró la publicación {n}. {lvl}",
    "detective.live.file": "Se mostró el expediente."
  }
});
