/* Hackles or Not?: generic, non-scary scenarios taken or adapted from the kit's lesson cards
   (3-5 Reproducibles R-3 Scam Sort and R-6 green flags, Spot the Fishy K-5 deck, Hackles Trail events).
   hackles: "up" | "down" | "unsure".  moves: which of pause / check / tell the kit recommends.
   Sensitive topics (secret chats with strangers, requests for pictures, threats) are left out on purpose. */
window.HK_DATA = window.HK_DATA || {};
window.HK_DATA.ornot = [
  { id: "N1", hackles: "up", moves: ["pause", "tell"],
    en: { text: "A game pop-up says: \"FREE COINS! Click this link in the next 5 minutes!\"", why: "A countdown is Pressure and free coins are an Offer too good to be true. Those are SPOT clues.", check: "Name the SPOT clues you see. Real prizes do not count down." },
    es: { text: "Una ventana emergente de un juego dice: “¡MONEDAS GRATIS! ¡Haz clic en este enlace en los próximos 5 minutos!”", why: "Una cuenta regresiva es Presión y las monedas gratis son una Oferta demasiado buena para ser verdad. Esas son pistas SPOT.", check: "Nombra las pistas SPOT que ves. Los premios de verdad no tienen cuenta regresiva." } },
  { id: "N2", hackles: "down", moves: [],
    en: { text: "Your teacher posts on the class page your family signed up for: \"Reading log due Friday.\"", why: "Known sender, normal ask, no secrets. Hackles down is a good answer.", check: "If you are ever unsure, ask your teacher in person." },
    es: { text: "Tu docente publica en la página de la clase a la que se inscribió tu familia: “El registro de lectura es para el viernes.”", why: "Remitente conocido, petición normal, sin secretos. Piel tranquila es una buena respuesta.", check: "Si alguna vez tienes dudas, pregúntale a tu docente en persona." } },
  { id: "N3", hackles: "down", moves: [],
    en: { text: "A friend you know from school says in the game you both play: \"Want to team up for the next round?\"", why: "You know them in person. Nothing odd, pushy or secret.", check: "You can always say no thanks." },
    es: { text: "Un amigo que conoces de la escuela dice en el juego que ambos juegan: “¿Quieres hacer equipo en la próxima ronda?”", why: "Lo conoces en persona. Nada raro, insistente ni secreto.", check: "Siempre puedes decir no, gracias." } },
  { id: "N4", hackles: "up", moves: ["pause", "check", "tell"],
    en: { text: "A text from a number nobody saved says: \"Hi, it's me, your friend! Click this link to see a funny video!\"", why: "It pretends to be a friend and brings a link. Pause before you tap.", check: "Ask your real friend in person or another way you already use." },
    es: { text: "Un mensaje de un número que nadie guardó dice: “¡Hola, soy yo, tu amigo! ¡Haz clic en este enlace para ver un video gracioso!”", why: "Finge ser un amigo y trae un enlace. Haz pausa antes de tocar.", check: "Pregúntale a tu amigo de verdad en persona o de otra manera que ya uses." } },
  { id: "N5", hackles: "up", moves: ["pause", "tell"],
    en: { text: "A player says: \"Give me your game password and I will add 5,000 gems to your account.\"", why: "Passwords are only for you and a trusted grown-up. Nobody needs yours to give you a gift.", check: "No check is needed. Do not share it." },
    es: { text: "Un jugador dice: “Dame tu contraseña del juego y te agrego 5,000 gemas a tu cuenta.”", why: "Las contraseñas son solo para ti y un adulto de confianza. Nadie necesita la tuya para darte un regalo.", check: "No hace falta revisar. No la compartas." } },
  { id: "N6", hackles: "unsure", moves: ["pause", "tell"],
    en: { text: "A notice inside your game says: \"An update is ready. Ask a grown-up to update from the official store.\"", why: "It might be fine. It asks you to involve a grown-up, which is a good sign. Pausing and asking is the safe move.", check: "A grown-up can update from the official store, not from a link." },
    es: { text: "Un aviso dentro de tu juego dice: “Hay una actualización lista. Pídele a un adulto que actualice desde la tienda oficial.”", why: "Podría estar bien. Pide que participe un adulto, y eso es buena señal. Hacer pausa y preguntar es la jugada segura.", check: "Un adulto puede actualizar desde la tienda oficial, no desde un enlace." } },
  { id: "N7", hackles: "up", moves: ["pause", "tell"],
    en: { text: "A video says: \"Don't tell your grown-up. This prize is our secret!\"", why: "A real prize never needs a secret. Secrets are a hackles-up clue.", check: "Name the S in SPOT: Secret." },
    es: { text: "Un video dice: “No le cuentes a tu adulto. ¡Este premio es nuestro secreto!”", why: "Un premio de verdad nunca necesita un secreto. Los secretos son una pista de piel erizada.", check: "Nombra la S de SPOT: Secreto." } },
  { id: "N8", hackles: "down", moves: [],
    en: { text: "Grandma sends a photo of her cat in a hat through the family chat that your grown-up set up.", why: "Known sender, set up by a grown-up, nothing asked of you.", check: "Enjoy the cat." },
    es: { text: "La abuela te manda una foto de su gato con sombrero por el chat de la familia que armó tu adulto.", why: "Remitente conocido, armado por un adulto, no te piden nada.", check: "Disfruta al gato." } },
  { id: "N9", hackles: "unsure", moves: ["pause", "check"],
    en: { text: "A friend at school sends a link with no words: \"Click!\"", why: "It might be your friend and it might not. A link with no words could mean their account was taken over.", check: "Ask your friend in person before you click." },
    es: { text: "Un amigo de la escuela manda un enlace sin palabras: “¡Clic!”", why: "Podría ser tu amigo y podría no serlo. Un enlace sin palabras puede significar que le tomaron la cuenta.", check: "Pregúntale a tu amigo en persona antes de hacer clic." } },
  { id: "N10", hackles: "unsure", moves: ["pause", "check", "tell"],
    en: { text: "A picture shows a giant cat taller than a building. It looks real.", why: "Pictures can be made up. You cannot tell from the picture alone.", check: "Ask \"Is this real?\" Look for who posted it and a second source." },
    es: { text: "Una imagen muestra un gato gigante más alto que un edificio. Parece real.", why: "Las imágenes pueden ser inventadas. No se puede saber solo con la imagen.", check: "Pregunta “¿Esto es real?” Busca quién la publicó y una segunda fuente." } },
  { id: "N11", hackles: "unsure", moves: ["pause", "tell"],
    en: { text: "A website asks: \"Enter your name and age to continue.\"", why: "A grown-up decides if that is OK. Private details are not for pop-up boxes.", check: "Ask a grown-up what to use. A silly name is often enough." },
    es: { text: "Un sitio web pide: “Escribe tu nombre y tu edad para continuar.”", why: "Un adulto decide si eso está bien. Los datos privados no son para cuadros emergentes.", check: "Pregúntale a un adulto qué usar. A menudo basta un nombre gracioso." } },
  { id: "N12", hackles: "up", moves: ["pause", "tell"],
    en: { text: "A quiz says: \"Which animal are you? Type your name, school and birthday to see!\"", why: "A silly quiz that wants private info is a Trick to move you.", check: "Skip it. A real quiz does not need your school." },
    es: { text: "Un cuestionario dice: “¿Qué animal eres? ¡Escribe tu nombre, tu escuela y tu cumpleaños para verlo!”", why: "Un cuestionario tonto que pide información privada es un Truco para hacerte actuar.", check: "Sáltalo. Un cuestionario de verdad no necesita tu escuela." } },
  { id: "N13", hackles: "down", moves: [],
    en: { text: "Your library's page says: \"Library cards expire in June. Ask at the desk to renew.\"", why: "Known place, nothing rushed, and it sends you to a person in the library.", check: "Ask at the desk, as the page says." },
    es: { text: "La página de tu biblioteca dice: “Los carnés vencen en junio. Pregunta en el mostrador para renovar.”", why: "Lugar conocido, sin prisa, y te manda con una persona de la biblioteca.", check: "Pregunta en el mostrador, como dice la página." } },
  { id: "N14", hackles: "unsure", moves: ["pause", "check", "tell"],
    en: { text: "A message says \"Hi, it's Grandpa!\" but it comes from a number nobody saved.", why: "It might be Grandpa and it might not.", check: "Call Grandpa the way you always do, on a number you already have." },
    es: { text: "Un mensaje dice “¡Hola, soy el abuelo!” pero viene de un número que nadie guardó.", why: "Podría ser el abuelo y podría no serlo.", check: "Llama al abuelo como siempre, a un número que ya tienes." } },
  { id: "N15", hackles: "up", moves: ["pause", "tell"],
    en: { text: "A pop-up says: \"Your tablet has a problem! Tap here to fix it right now!\"", why: "Tablets do not talk to you like that. This is Pressure and a Trick.", check: "Close it or find a grown-up. Do not tap." },
    es: { text: "Una ventana emergente dice: “¡Tu tableta tiene un problema! ¡Toca aquí para arreglarlo ya!”", why: "Las tabletas no te hablan así. Esto es Presión y un Truco.", check: "Ciérrala o busca a un adulto. No toques." } },
  { id: "N16", hackles: "unsure", moves: ["pause", "tell"],
    en: { text: "A game asks: \"Use your location?\"", why: "A big ask. A grown-up decides what to share.", check: "Ask a grown-up. Your location is a privacy shell." },
    es: { text: "Un juego pregunta: “¿Usar tu ubicación?”", why: "Una petición grande. Un adulto decide qué compartir.", check: "Pregúntale a un adulto. Tu ubicación es una concha de privacidad." } },
  { id: "N17", hackles: "down", moves: [],
    en: { text: "The coach's team chat says: \"Practice is canceled due to rain.\"", why: "Known chat, no rush, nothing asked of you.", check: "If you want to be sure, ask your coach in person." },
    es: { text: "El chat del equipo del entrenador dice: “Se cancela la práctica por lluvia.”", why: "Chat conocido, sin prisa, no te piden nada.", check: "Si quieres estar seguro, pregúntale a tu entrenador en persona." } },
  { id: "N18", hackles: "up", moves: ["pause", "tell"],
    en: { text: "You click a link by mistake and a strange page opens. You feel worried.", why: "That worried feeling is your hackles. Everyone clicks the wrong thing sometimes. Telling is the strongest move and there is no blame.", check: "Close the page and say: \"Something happened and I'm not sure what to do.\"" },
    es: { text: "Haces clic en un enlace por error y se abre una página rara. Te sientes preocupado.", why: "Esa sensación de preocupación es tu piel erizada. Todos hacemos clic donde no es a veces. Contar es la jugada más fuerte y no hay culpa.", check: "Cierra la página y di: “Pasó algo y no sé qué hacer.”" } },
  { id: "N19", hackles: "up", moves: ["pause", "tell"],
    en: { text: "Someone posts a silly picture of a classmate in the class chat.", why: "A joke can hurt. Do not share it. Tell a trusted adult, and be kind to your classmate.", check: "Keep it (do not pass it on) and tell." },
    es: { text: "Alguien publica una foto tonta de un compañero en el chat de la clase.", why: "Una broma puede doler. No la compartas. Cuéntaselo a un adulto de confianza y sé amable con tu compañero.", check: "No la pases a otros y cuéntalo." } },
  { id: "N20", hackles: "up", moves: ["pause", "check", "tell"],
    en: { text: "A message says: \"Your friend is in trouble! Click here NOW to help!\"", why: "Real friends in trouble tell a grown-up in person. This is Pressure.", check: "Ask your friend in person, then tell a grown-up." },
    es: { text: "Un mensaje dice: “¡Tu amigo está en problemas! ¡Haz clic aquí YA para ayudar!”", why: "Los amigos que de verdad están en problemas se lo cuentan a un adulto en persona. Esto es Presión.", check: "Pregúntale a tu amigo en persona y luego cuéntaselo a un adulto." } }
];
