/* Hackles or Not?: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "ornot.title": "Hackles or Not?",
    "ornot.kicker": "Plate 5 of 6",
    "ornot.lead": "Your hackles are what rise when something feels off. Read a short situation, decide if your hackles go up, then choose your moves: Pause, Check, Tell. A false alarm is always fine.",
    "ornot.tab.gut": "Gut check",
    "ornot.tab.ladder": "Help Ladder practice",
    "ornot.moves.h": "The three moves",
    "ornot.m.pause": "Pause",
    "ornot.m.check": "Check",
    "ornot.m.tell": "Tell",
    "ornot.m.pause.d": "Stop. Hands off. Take one slow breath. Nothing online is so urgent it cannot wait ten seconds.",
    "ornot.m.check.d": "Look for clues. Check another way, not with the link or number in the message.",
    "ornot.m.tell.d": "Tell a trusted adult. Telling is always safe, even if you already clicked.",
    "ornot.start": "Start 8 situations",
    "ornot.card": "Situation {n} of {total}",
    "ornot.q": "Do your hackles go up?",
    "ornot.up": "Hackles up",
    "ornot.up.d": "Something feels odd, too good, pushy, secret or scary.",
    "ornot.down": "Hackles down",
    "ornot.down.d": "This feels normal and safe.",
    "ornot.unsure": "Not sure",
    "ornot.unsure.d": "I can't tell. That is a smart answer.",
    "ornot.r.match": "Our view matches yours.",
    "ornot.r.false_alarm": "A false alarm is fine. Noticing a feeling is the skill. This one looks safe, and it is good to check first.",
    "ornot.r.unsure_ok": "Not sure is a smart answer. When you cannot tell, you pause and check.",
    "ornot.r.missed": "Good try. This one is easy to miss. Here is the clue to notice next time.",
    "ornot.r.cant_tell": "This one is tricky. You cannot tell from the message alone, so pausing is the safe move.",
    "ornot.r.up_for_unsure": "Good caution. You cannot tell from the message alone, so pausing and checking is right.",
    "ornot.kit": "The kit's view: {v}",
    "ornot.v.up": "Hackles up",
    "ornot.v.down": "Hackles down",
    "ornot.v.unsure": "Not sure, so pause and check",
    "ornot.pick": "Which moves would you choose? Pick any that fit, then see what the kit recommends.",
    "ornot.show": "Show what the kit recommends",
    "ornot.rec": "What the kit recommends",
    "ornot.recNone": "No moves needed here. Extra care is never wrong.",
    "ornot.cmp.exact": "You chose the same moves. Nice noticing!",
    "ornot.cmp.extra": "You chose everything the kit does, plus more. Extra care is never wrong.",
    "ornot.cmp.partial": "You have a good start. The kit would also add: {m}.",
    "ornot.cmp.none": "Here is what the kit would do. Every attempt is practice, and nobody is graded.",
    "ornot.cmp.noneNeeded": "You chose no moves, which fits. Extra care would be fine too.",
    "ornot.cmp.noneNeededExtra": "The kit would not need any moves here, and your care is fine too.",
    "ornot.why": "Why",
    "ornot.how": "How to check or what to say",
    "ornot.next": "Next situation",
    "ornot.finish": "Finish",
    "ornot.end.h": "Nice noticing, Hackles Crew",
    "ornot.end.b": "You practiced {n} situations. Hackles up? Pause. Check. Tell.",
    "ornot.end.k": "False alarms are fine. A mistake is never your fault. If anything online ever worries you, tell a trusted adult.",
    "ornot.again": "Play again",
    "ornot.ladder": "Go to Help Ladder practice",
    "ornot.lab": "Back to Lab home",
    "ornot.chosen": "chosen",

    "ornot.lad.h": "Help Ladder practice",
    "ornot.lad.b": "The Help Ladder has rungs: you (pause), a friend, a trusted adult, a report. The Next-Rung Rule says if the first person does not help, you are not done. Keep climbing until someone helps.",
    "ornot.lad.rungs": "The rungs",
    "ornot.lad.r1": "You: pause",
    "ornot.lad.r2": "A friend who can come with you",
    "ornot.lad.r3": "A trusted adult",
    "ornot.lad.r4": "A report: the report button, school staff or a helpline",
    "ornot.lad.start": "Practice the Next-Rung Rule",
    "ornot.lad.card": "Practice {n} of {total}",
    "ornot.lad.scene": "What happened",
    "ornot.lad.first": "What happened when they told someone first",
    "ornot.lad.q": "What do you do next?",
    "ornot.lad.good": "Yes. Keep climbing. You are not done until someone helps.",
    "ornot.lad.try": "Good try. Everyone feels tempted to stop sometimes. The Next-Rung Rule says keep climbing, so here is the move that does that.",
    "ornot.lad.say": "Sentences you can say:",
    "ornot.lad.s1": "I need help with something online.",
    "ornot.lad.s2": "Something happened and I'm not sure what to do.",
    "ornot.lad.s3": "I'm not in trouble. I just need to tell you something.",
    "ornot.lad.reply": "A good grown-up reply: \"Thank you for telling me. It is not your fault. Let's figure it out together.\"",
    "ornot.lad.nextq": "Next practice",
    "ornot.lad.done": "You practiced climbing the Help Ladder. Telling is never getting in trouble.",
    "ornot.live.card": "Situation {n} of {total}. {t}",
    "ornot.live.reveal": "{r}"
  },
  es: {
    "ornot.title": "¿Piel erizada o no?",
    "ornot.kicker": "Lámina 5 de 6",
    "ornot.lead": "La piel erizada es lo que se levanta cuando algo se siente raro. Lee una situación corta, decide si se te eriza la piel y elige tus movimientos: Pausa, Revisa, Cuenta. Una falsa alarma siempre está bien.",
    "ornot.tab.gut": "Corazonada",
    "ornot.tab.ladder": "Práctica de la Escalera de Ayuda",
    "ornot.moves.h": "Los tres movimientos",
    "ornot.m.pause": "Pausa",
    "ornot.m.check": "Revisa",
    "ornot.m.tell": "Cuenta",
    "ornot.m.pause.d": "Para. Manos quietas. Respira lento una vez. Nada en línea es tan urgente que no pueda esperar diez segundos.",
    "ornot.m.check.d": "Busca pistas. Revisa de otra manera, no con el enlace ni el número del mensaje.",
    "ornot.m.tell.d": "Cuéntale a un adulto de confianza. Contar siempre es seguro, aunque ya hayas hecho clic.",
    "ornot.start": "Empezar 8 situaciones",
    "ornot.card": "Situación {n} de {total}",
    "ornot.q": "¿Se te eriza la piel?",
    "ornot.up": "Piel erizada",
    "ornot.up.d": "Algo se siente raro, demasiado bueno, insistente, secreto o de miedo.",
    "ornot.down": "Piel tranquila",
    "ornot.down.d": "Esto se siente normal y seguro.",
    "ornot.unsure": "No estoy seguro",
    "ornot.unsure.d": "No puedo saberlo. Esa es una respuesta inteligente.",
    "ornot.r.match": "Nuestra opinión coincide con la tuya.",
    "ornot.r.false_alarm": "Una falsa alarma está bien. Notar una sensación es la habilidad. Esta parece segura, y está bien revisar primero.",
    "ornot.r.unsure_ok": "No estoy seguro es una respuesta inteligente. Cuando no puedes saberlo, haces pausa y revisas.",
    "ornot.r.missed": "Buen intento. Esta es fácil de pasar por alto. Esta es la pista para notar la próxima vez.",
    "ornot.r.cant_tell": "Esta es difícil. No se puede saber solo con el mensaje, así que hacer pausa es la jugada segura.",
    "ornot.r.up_for_unsure": "Buena precaución. No se puede saber solo con el mensaje, así que hacer pausa y revisar es lo correcto.",
    "ornot.kit": "La opinión del kit: {v}",
    "ornot.v.up": "Piel erizada",
    "ornot.v.down": "Piel tranquila",
    "ornot.v.unsure": "No se sabe, así que pausa y revisa",
    "ornot.pick": "¿Qué movimientos elegirías? Elige los que encajen y luego mira qué recomienda el kit.",
    "ornot.show": "Mostrar lo que recomienda el kit",
    "ornot.rec": "Lo que recomienda el kit",
    "ornot.recNone": "Aquí no hacen falta movimientos. Cuidarse de más nunca está mal.",
    "ornot.cmp.exact": "Elegiste los mismos movimientos. ¡Buen ojo!",
    "ornot.cmp.extra": "Elegiste todo lo que hace el kit y algo más. Cuidarse de más nunca está mal.",
    "ornot.cmp.partial": "Vas bien. El kit también añadiría: {m}.",
    "ornot.cmp.none": "Esto es lo que haría el kit. Cada intento es práctica y nadie recibe nota.",
    "ornot.cmp.noneNeeded": "No elegiste movimientos, y eso encaja. Cuidarse de más también estaría bien.",
    "ornot.cmp.noneNeededExtra": "El kit aquí no necesitaría movimientos, y tu cuidado también está bien.",
    "ornot.why": "Por qué",
    "ornot.how": "Cómo revisar o qué decir",
    "ornot.next": "Siguiente situación",
    "ornot.finish": "Terminar",
    "ornot.end.h": "Buen ojo, Tripulación Hackles",
    "ornot.end.b": "Practicaste {n} situaciones. ¿Se te eriza la piel? Pausa. Revisa. Cuenta.",
    "ornot.end.k": "Las falsas alarmas están bien. Un error nunca es tu culpa. Si algo en línea te preocupa, cuéntaselo a un adulto de confianza.",
    "ornot.again": "Jugar otra vez",
    "ornot.ladder": "Ir a la práctica de la Escalera de Ayuda",
    "ornot.lab": "Volver al inicio del Laboratorio",
    "ornot.chosen": "elegido",

    "ornot.lad.h": "Práctica de la Escalera de Ayuda",
    "ornot.lad.b": "La Escalera de Ayuda tiene peldaños: tú (pausa), un amigo, un adulto de confianza, una denuncia. La Regla del Siguiente Peldaño dice que si la primera persona no ayuda, no has terminado. Sigue subiendo hasta que alguien ayude.",
    "ornot.lad.rungs": "Los peldaños",
    "ornot.lad.r1": "Tú: pausa",
    "ornot.lad.r2": "Un amigo que pueda acompañarte",
    "ornot.lad.r3": "Un adulto de confianza",
    "ornot.lad.r4": "Una denuncia: el botón de reportar, el personal de la escuela o una línea de ayuda",
    "ornot.lad.start": "Practicar la Regla del Siguiente Peldaño",
    "ornot.lad.card": "Práctica {n} de {total}",
    "ornot.lad.scene": "Lo que pasó",
    "ornot.lad.first": "Lo que pasó cuando se lo contó a alguien primero",
    "ornot.lad.q": "¿Qué haces ahora?",
    "ornot.lad.good": "Sí. Sigue subiendo. No has terminado hasta que alguien ayude.",
    "ornot.lad.try": "Buen intento. A todos nos tienta parar a veces. La Regla del Siguiente Peldaño dice que sigas subiendo, así que esta es la jugada que lo hace.",
    "ornot.lad.say": "Frases que puedes decir:",
    "ornot.lad.s1": "Necesito ayuda con algo en línea.",
    "ornot.lad.s2": "Pasó algo y no sé qué hacer.",
    "ornot.lad.s3": "No estoy en problemas. Solo necesito contarte algo.",
    "ornot.lad.reply": "Una buena respuesta de un adulto: “Gracias por contármelo. No es tu culpa. Vamos a resolverlo juntos.”",
    "ornot.lad.nextq": "Siguiente práctica",
    "ornot.lad.done": "Practicaste subir la Escalera de Ayuda. Contar nunca te mete en problemas.",
    "ornot.live.card": "Situación {n} de {total}. {t}",
    "ornot.live.reveal": "{r}"
  }
});
