/* Generated by _build/build_data.py from the kit's Markdown. Do not edit by hand. */
window.HK_DATA = window.HK_DATA || {};
window.HK_DATA.spot = {
 "k5": [
  {
   "id": "K1",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "O",
    "P"
   ],
   "en": {
    "front": "A pop-up on a game says: \"YOU WON A PONY! TAP NOW! Only 5 seconds left!\"",
    "back": "**P**ressure and **O**ffer too good. Pause. Do not tap. Tell a grown-up."
   },
   "es": {
    "front": "Una ventana emergente en un juego dice: “¡GANASTE UN PONI! ¡TOCA YA! ¡Solo quedan 5 segundos!”",
    "back": "**P**resión y **O**ferta demasiado buena. Pausa. No toques. Cuéntaselo a un adulto."
   }
  },
  {
   "id": "K2",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A message in game chat: \"Free 1,000 gems! Click here and tell me your password so I can put them in your account.\"",
    "back": "**T**rick: asks for a password. Passwords are only for you and a trusted grown-up. Tell."
   },
   "es": {
    "front": "Un mensaje en el chat del juego dice: “¡1,000 gemas gratis! Haz clic aquí y dime tu contraseña para ponerlas en tu cuenta.”",
    "back": "**T**ruco: te pide una contraseña. Las contraseñas son solo para ti y un adulto de confianza. Cuenta."
   }
  },
  {
   "id": "K3",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "S"
   ],
   "en": {
    "front": "A video says: \"Don't tell your grown-up. This prize is our secret!\"",
    "back": "**S**ecret. A real prize never needs a secret. Pause and tell."
   },
   "es": {
    "front": "Un video dice: “No le cuentes a tu adulto. ¡Este premio es nuestro secreto!”",
    "back": "**S**ecreto. Un premio de verdad nunca necesita un secreto. Pausa y cuenta."
   }
  },
  {
   "id": "K4",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "P",
    "T"
   ],
   "en": {
    "front": "A pop-up says: \"Your tablet has a problem! Tap here to fix it right now!\"",
    "back": "**P**ressure and **T**rick. Tablets do not talk to you like that. Pause, find a grown-up."
   },
   "es": {
    "front": "Una ventana emergente dice: “¡Tu tableta tiene un problema! ¡Toca aquí para arreglarlo ya!”",
    "back": "**P**resión y **T**ruco. Las tabletas no te hablan así. Pausa y busca a un adulto."
   }
  },
  {
   "id": "K5",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "O"
   ],
   "en": {
    "front": "A grown-up's email says: \"Congratulations! You are our one-millionth visitor! Claim your prize!\"",
    "back": "**O**ffer too good. Nobody gives a prize to the millionth visitor. Show the email to a grown-up."
   },
   "es": {
    "front": "El correo de un adulto dice: “¡Felicidades! ¡Eres nuestro visitante número un millón! ¡Reclama tu premio!”",
    "back": "**O**ferta demasiado buena. Nadie regala un premio al visitante un millón. Muéstrale el correo a un adulto."
   }
  },
  {
   "id": "K6",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A player called CoolKid2012 says: \"I'll give you rare skins if you give me your login.\"",
    "back": "**T**rick: trading for your login. Pause, do not answer, tell a grown-up."
   },
   "es": {
    "front": "Un jugador llamado CoolKid2012 dice: “Te doy skins raros si me das tu usuario y contraseña.”",
    "back": "**T**ruco: quiere cambiar cosas por tu acceso. Pausa, no respondas y cuéntaselo a un adulto."
   }
  },
  {
   "id": "K7",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "O",
    "T"
   ],
   "en": {
    "front": "A pop-up says: \"Your game is out of lives! Type your name and birthday to get 50 free lives.\"",
    "back": "**O**ffer and **T**rick: it wants private info. Pause. Never type name or birthday into a pop-up."
   },
   "es": {
    "front": "Una ventana emergente dice: “¡Tu juego se quedó sin vidas! Escribe tu nombre y tu cumpleaños para recibir 50 vidas gratis.”",
    "back": "**O**ferta y **T**ruco: quiere información privada. Pausa. Nunca escribas tu nombre ni tu cumpleaños en una ventana emergente."
   }
  },
  {
   "id": "K8",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A text from a number nobody saved says: \"Hi! It's me, your friend! Click this link to see a funny video!\"",
    "back": "**T**rick: pretending to be a friend, plus a link. Pause. Ask the real friend a different way."
   },
   "es": {
    "front": "Un mensaje de un número que nadie guardó dice: “¡Hola! Soy yo, tu amigo. ¡Haz clic en este enlace para ver un video gracioso!”",
    "back": "**T**ruco: finge ser un amigo y trae un enlace. Pausa. Pregúntale a tu amigo de verdad de otra manera."
   }
  },
  {
   "id": "K10",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A pop-up says: \"Your grown-up said it's OK to get this free game! Tap YES!\"",
    "back": "**T**rick: claims permission. Only ask your grown-up in person."
   },
   "es": {
    "front": "Una ventana emergente dice: “¡Tu adulto dijo que está bien bajar este juego gratis! ¡Toca SÍ!”",
    "back": "**T**ruco: dice que tienes permiso. Solo pregúntale a tu adulto en persona."
   }
  },
  {
   "id": "K11",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "S"
   ],
   "en": {
    "front": "A chat helper says: \"I'm your friend. Tell me your secrets and I will never tell anyone.\"",
    "back": "**S**ecret. A program is not a friend and cannot keep secrets safe. Tell your grown-up."
   },
   "es": {
    "front": "Un ayudante del chat dice: “Soy tu amigo. Cuéntame tus secretos y nunca se los diré a nadie.”",
    "back": "**S**ecreto. Un programa no es un amigo y no puede guardar bien tus secretos. Cuéntaselo a tu adulto."
   }
  },
  {
   "id": "K12",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A game message says: \"Your parent told me to tell you to type your family's card number.\"",
    "back": "**T**rick. Grown-ups never ask kids for card numbers this way. Pause. Tell."
   },
   "es": {
    "front": "Un mensaje del juego dice: “Tu mamá o tu papá me dijo que te pida el número de la tarjeta de tu familia.”",
    "back": "**T**ruco. Los adultos nunca les piden a los niños el número de una tarjeta así. Pausa. Cuenta."
   }
  },
  {
   "id": "K13",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "O"
   ],
   "en": {
    "front": "A pop-up shows a shiny gold gift box and says: \"TAP THE BOX FOR YOUR PRIZE!\"",
    "back": "**O**ffer too good. That is the Too-Good Box! Do not tap. Wave hello and tell a grown-up."
   },
   "es": {
    "front": "Una ventana emergente muestra una caja de regalo dorada y brillante y dice: “¡TOCA LA CAJA PARA TU PREMIO!”",
    "back": "**O**ferta demasiado buena. ¡Es la Caja Demasiado Buena! No la toques. Saluda con la mano y cuéntaselo a un adulto."
   }
  },
  {
   "id": "K15",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "O",
    "T"
   ],
   "en": {
    "front": "A prize wheel says: \"Everybody wins! Type your home address to get your prize.\"",
    "back": "**O**ffer and **T**rick: wants your address. Pause. Tell."
   },
   "es": {
    "front": "Una ruleta de premios dice: “¡Todos ganan! Escribe la dirección de tu casa para recibir tu premio.”",
    "back": "**O**ferta y **T**ruco: quiere tu dirección. Pausa. Cuenta."
   }
  },
  {
   "id": "K16",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A message says: \"I'm new at your school! Give me your password so I can see your profile.\"",
    "back": "**T**rick. New kids can ask a teacher. Never share a password. Tell."
   },
   "es": {
    "front": "Un mensaje dice: “¡Soy nuevo en tu escuela! Dame tu contraseña para ver tu perfil.”",
    "back": "**T**ruco. Los niños nuevos pueden preguntarle a un docente. Nunca compartas una contraseña. Cuenta."
   }
  },
  {
   "id": "K17",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "P",
    "T"
   ],
   "en": {
    "front": "A pop-up says: \"Free in-game money! Hurry! Type your grown-up's card number!\"",
    "back": "**P**ressure and **T**rick. Never type a card number. Tell a grown-up."
   },
   "es": {
    "front": "Una ventana emergente dice: “¡Dinero gratis en el juego! ¡Rápido! ¡Escribe el número de la tarjeta de tu adulto!”",
    "back": "**P**resión y **T**ruco. Nunca escribas el número de una tarjeta. Cuéntaselo a un adulto."
   }
  },
  {
   "id": "K18",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "P"
   ],
   "en": {
    "front": "A message says: \"Your friend is in trouble! Click here NOW to help!\"",
    "back": "**P**ressure. Real friends in trouble tell a grown-up in person. Pause, then Tell."
   },
   "es": {
    "front": "Un mensaje dice: “¡Tu amigo está en problemas! ¡Haz clic aquí YA para ayudar!”",
    "back": "**P**resión. Los amigos que de verdad están en problemas se lo cuentan a un adulto en persona. Pausa y luego cuenta."
   }
  },
  {
   "id": "K19",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A picture shows a dog that looks real, standing up and talking like a person. The caption says: \"A REAL talking dog!\"",
    "back": "Pretend picture. Pictures can be made up. Pause and ask a grown-up \"Is this real?\""
   },
   "es": {
    "front": "Una imagen muestra un perro que parece real, de pie y hablando como una persona. El texto dice: “¡Un perro que habla DE VERDAD!”",
    "back": "Imagen inventada. Las imágenes pueden ser inventadas. Pausa y pregúntale a un adulto: “¿Esto es real?”"
   }
  },
  {
   "id": "K20",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "T"
   ],
   "en": {
    "front": "A quiz says: \"Which animal are you? Type your name, school and birthday to see!\"",
    "back": "**T**rick: wants private info for a silly quiz. Pause. Tell."
   },
   "es": {
    "front": "Un cuestionario dice: “¿Qué animal eres? Escribe tu nombre, tu escuela y tu cumpleaños para verlo.”",
    "back": "**T**ruco: pide información privada para un cuestionario tonto. Pausa. Cuenta."
   }
  },
  {
   "id": "K21",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "S"
   ],
   "en": {
    "front": "A game player says: \"Let's race to the prize! Don't tell grown-ups, they ruin it.\"",
    "back": "**S**ecret. Pause and tell. Good games are fine to share."
   },
   "es": {
    "front": "Un jugador del juego dice: “Vamos a una carrera por el premio. No les cuentes a los adultos, lo arruinan.”",
    "back": "**S**ecreto. Pausa y cuenta. Los juegos buenos se pueden compartir."
   }
  },
  {
   "id": "K22",
   "sort": "F",
   "star": true,
   "heavy": false,
   "flags": [
    "P"
   ],
   "en": {
    "front": "A pop-up flashes: \"ONLY 10 SECONDS LEFT TO BE A WINNER!\"",
    "back": "**P**ressure. Real prizes do not count down. Pause."
   },
   "es": {
    "front": "Una ventana emergente parpadea: “¡SOLO QUEDAN 10 SEGUNDOS PARA SER GANADOR!”",
    "back": "**P**resión. Los premios de verdad no tienen cuenta regresiva. Pausa."
   }
  },
  {
   "id": "K23",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your teacher says on the class page: \"Story time is at 2. Bring your blue book bag.\"",
    "back": "Known sender, normal ask, no secrets. Real! Hackles down."
   },
   "es": {
    "front": "Tu docente dice en la página de la clase: “La hora del cuento es a las 2. Trae tu mochila azul de libros.”",
    "back": "Remitente conocido, petición normal, sin secretos. ¡Es real! Piel tranquila."
   }
  },
  {
   "id": "K24",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Grandma sends a photo of her cat in a hat, through the family chat that your grown-up set up.",
    "back": "Known sender, fun, set up by a grown-up. Real!"
   },
   "es": {
    "front": "La abuela te manda una foto de su gato con sombrero por el chat de la familia que armó tu adulto.",
    "back": "Remitente conocido, divertido, armado por un adulto. ¡Es real!"
   }
  },
  {
   "id": "K25",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The library's note to your grown-up says: \"Your book is ready.\"",
    "back": "Known place, expected. Real."
   },
   "es": {
    "front": "La nota de la biblioteca para tu adulto dice: “Tu libro está listo.”",
    "back": "Un lugar conocido y esperado. Real."
   }
  },
  {
   "id": "K26",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your mom says: \"You can play your game for 20 minutes after dinner.\"",
    "back": "A trusted grown-up in person. Real."
   },
   "es": {
    "front": "Tu mamá dice: “Puedes jugar 20 minutos después de la cena.”",
    "back": "Un adulto de confianza en persona. Real."
   }
  },
  {
   "id": "K27",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "After your grown-up installed it, a game says: \"Update ready: new hats!\"",
    "back": "Set up by a grown-up, asks for nothing. Real."
   },
   "es": {
    "front": "Después de que tu adulto lo instaló, un juego dice: “Actualización lista: ¡sombreros nuevos!”",
    "back": "Armado por un adulto y no pide nada. Real."
   }
  },
  {
   "id": "K28",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A video call from your aunt, with your grown-up sitting next to you.",
    "back": "Known person, a grown-up nearby. Real."
   },
   "es": {
    "front": "Una videollamada de tu tía, con tu adulto sentado a tu lado.",
    "back": "Persona conocida y un adulto cerca. Real."
   }
  },
  {
   "id": "K29",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The school page says: \"Picture Day is Friday.\"",
    "back": "Known school page. Real."
   },
   "es": {
    "front": "La página de la escuela dice: “El día de las fotos es el viernes.”",
    "back": "Página conocida de la escuela. Real."
   }
  },
  {
   "id": "K30",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The family weather app says: \"Rain this afternoon.\"",
    "back": "No ask, no secret. Real."
   },
   "es": {
    "front": "La aplicación del clima de la familia dice: “Lluvia esta tarde.”",
    "back": "No pide nada y no hay secretos. Real."
   }
  },
  {
   "id": "K31",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your grown-up's saved contact sends a pizza sticker to the family chat that your grown-up set up.",
    "back": "Saved contact, family chat set up by a grown-up, no ask. Real."
   },
   "es": {
    "front": "Un contacto guardado de tu adulto manda una calcomanía de pizza al chat de la familia que armó tu adulto.",
    "back": "Contacto guardado, chat de la familia armado por un adulto, no pide nada. Real."
   }
  },
  {
   "id": "K32",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A teammate you know at school says in the class game: \"Good game! Play again at recess?\"",
    "back": "You know them in person. Real."
   },
   "es": {
    "front": "Un compañero de la escuela que conoces dice en el juego de la clase: “¡Buen juego! ¿Jugamos otra vez en el recreo?”",
    "back": "Lo conoces en persona. Real."
   }
  },
  {
   "id": "K33",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The family tablet says: \"Time's up! Screen break time.\"",
    "back": "A timer your grown-up set. Real. Ember says: stretch!"
   },
   "es": {
    "front": "La tableta de la familia dice: “¡Se acabó el tiempo! Hora de descansar de la pantalla.”",
    "back": "Un temporizador que puso tu adulto. Real. Ember dice: ¡estírate!"
   }
  },
  {
   "id": "K34",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The reading app your teacher picked says: \"Press play to hear the story.\"",
    "back": "Teacher-chosen, no private info. Real."
   },
   "es": {
    "front": "La aplicación de lectura que eligió tu docente dice: “Oprime play para escuchar el cuento.”",
    "back": "Elegida por tu docente, sin información privada. Real."
   }
  },
  {
   "id": "K35",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A drawing app asks: \"Do you want to save your picture?\"",
    "back": "A normal question. Real. (You can ask a grown-up where it is saved.)"
   },
   "es": {
    "front": "Una aplicación de dibujo pregunta: “¿Quieres guardar tu dibujo?”",
    "back": "Una pregunta normal. Real. (Puedes preguntarle a un adulto dónde se guarda.)"
   }
  },
  {
   "id": "K36",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your coach emails your grown-ups: \"Practice moved to 4 pm.\"",
    "back": "Known coach, email to grown-ups. Real."
   },
   "es": {
    "front": "Tu entrenador les escribe a tus adultos: “La práctica cambió a las 4 pm.”",
    "back": "Entrenador conocido, correo para adultos. Real."
   }
  },
  {
   "id": "K37",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A birthday video from your cousin, sent to your grown-up's phone.",
    "back": "Known family. Real."
   },
   "es": {
    "front": "Un video de cumpleaños de tu primo, enviado al teléfono de tu adulto.",
    "back": "Familia conocida. Real."
   }
  },
  {
   "id": "K38",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A math game your teacher gave says: \"Nice work! You finished level 2.\"",
    "back": "Teacher-chosen. Real."
   },
   "es": {
    "front": "Un juego de matemáticas que te dio tu docente dice: “¡Buen trabajo! Terminaste el nivel 2.”",
    "back": "Elegido por tu docente. Real."
   }
  },
  {
   "id": "K39",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A text to your grown-up from the doctor's office you visit says: \"Reminder: checkup tomorrow at 9.\"",
    "back": "Known place, no pressure. Real."
   },
   "es": {
    "front": "Un mensaje al teléfono de tu adulto del consultorio al que vas dice: “Recordatorio: chequeo mañana a las 9.”",
    "back": "Lugar conocido, sin presión. Real."
   }
  },
  {
   "id": "K40",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your big sister reads you a message from Grandpa: \"Happy birthday! Dinner at my house!\"",
    "back": "Known family, in person. Real."
   },
   "es": {
    "front": "Tu hermana mayor te lee un mensaje del abuelo: “¡Feliz cumpleaños! ¡Cena en mi casa!”",
    "back": "Familia conocida, en persona. Real."
   }
  },
  {
   "id": "K41",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A kids' video on your family's approved list says: \"Next video starts in 5 seconds.\"",
    "back": "A real feature. You can ask your grown-up to turn it off, so Pause is yours to use."
   },
   "es": {
    "front": "Un video infantil de la lista aprobada de tu familia dice: “El próximo video empieza en 5 segundos.”",
    "back": "Una función real. Puedes pedirle a tu adulto que la apague, así que la Pausa es tuya."
   }
  },
  {
   "id": "K42",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your teacher's class app says: \"Your teacher invited you to log in.\"",
    "back": "Real, teacher-given, with your grown-up or teacher helping."
   },
   "es": {
    "front": "La aplicación de clase de tu docente dice: “Tu docente te invitó a iniciar sesión.”",
    "back": "Real, dado por tu docente, con ayuda de tu adulto o tu docente."
   }
  },
  {
   "id": "K43",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A text from your best friend's parent, saved in your parent's phone: \"Can Omar come play Saturday?\"",
    "back": "Known grown-up, normal ask. Real."
   },
   "es": {
    "front": "Un mensaje al teléfono de tu mamá, de la mamá de tu mejor amigo, guardada en sus contactos: “¿Puede venir Omar a jugar el sábado?”",
    "back": "Adulto conocido, petición normal. Real."
   }
  },
  {
   "id": "K44",
   "sort": "R",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The class pet cam says: \"Hamster Hank is awake!\"",
    "back": "Silly and real. Real!"
   },
   "es": {
    "front": "La cámara de la mascota de la clase dice: “¡El hámster Hank está despierto!”",
    "back": "Graciosa y real. ¡Real!"
   }
  },
  {
   "id": "K45",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend request in a game from a player named Starlight7.",
    "back": "You don't know who it is. Pause. Ask a grown-up before saying yes."
   },
   "es": {
    "front": "Una solicitud de amistad en un juego de un jugador llamado Starlight7.",
    "back": "No sabes quién es. Pausa. Pregúntale a un adulto antes de decir que sí."
   }
  },
  {
   "id": "K46",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A message says: \"Hi, it's Grandpa!\" but from a number nobody saved.",
    "back": "It might be Grandpa; it might not. Pause. Check by calling Grandpa the way you always do."
   },
   "es": {
    "front": "Un mensaje dice: “¡Hola, soy el abuelo!” pero viene de un número que nadie guardó.",
    "back": "Podría ser el abuelo y podría no serlo. Pausa. Revisa llamando al abuelo como siempre lo haces."
   }
  },
  {
   "id": "K47",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A video ad says: \"Try our new free game!\"",
    "back": "Ads can be fun, but they are not from your grown-up. Pause. Ask."
   },
   "es": {
    "front": "Un anuncio en video dice: “¡Prueba nuestro nuevo juego gratis!”",
    "back": "Los anuncios pueden ser divertidos, pero no vienen de tu adulto. Pausa. Pregunta."
   }
  },
  {
   "id": "K48",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend at school sends a link with no words: \"Click!\"",
    "back": "Might be the friend; might not. Pause. Ask your friend in person."
   },
   "es": {
    "front": "Un amigo de la escuela manda un enlace sin palabras: “¡Clic!”",
    "back": "Podría ser tu amigo y podría no serlo. Pausa. Pregúntale a tu amigo en persona."
   }
  },
  {
   "id": "K49",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A pop-up asks: \"Allow this app to use your camera?\"",
    "back": "A big ask. Pause. Ask a grown-up."
   },
   "es": {
    "front": "Una ventana emergente pregunta: “¿Permitir que esta aplicación use tu cámara?”",
    "back": "Una petición grande. Pausa. Pregúntale a un adulto."
   }
  },
  {
   "id": "K50",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A message says: \"I'm from your school. What's your teacher's name?\"",
    "back": "Your school knows your teacher. Pause. Ask a grown-up."
   },
   "es": {
    "front": "Un mensaje dice: “Soy de tu escuela. ¿Cómo se llama tu docente?”",
    "back": "Tu escuela ya conoce a tu docente. Pausa. Pregúntale a un adulto."
   }
  },
  {
   "id": "K51",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A picture shows a giant cat taller than a building. It looks real.",
    "back": "Pictures can be made up. Ask \"Is this real?\" Check with a grown-up."
   },
   "es": {
    "front": "Una imagen muestra un gato gigante más alto que un edificio. Parece real.",
    "back": "Las imágenes pueden ser inventadas. Pregunta: “¿Es real?” Revisa con un adulto."
   }
  },
  {
   "id": "K52",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A website asks: \"Enter your name and age to continue.\"",
    "back": "Pause. A grown-up decides if that is OK."
   },
   "es": {
    "front": "Un sitio web pide: “Escribe tu nombre y tu edad para continuar.”",
    "back": "Pausa. Un adulto decide si eso está bien."
   }
  },
  {
   "id": "K53",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A new game says: \"Pick a name to play!\"",
    "back": "Pause. Ask a grown-up. A good name is silly and not your real name."
   },
   "es": {
    "front": "Un juego nuevo dice: “¡Elige un nombre para jugar!”",
    "back": "Pausa. Pregúntale a un adulto. Un buen nombre es gracioso y no es tu nombre de verdad."
   }
  },
  {
   "id": "K54",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A video voice says: \"Subscribe for a surprise!\"",
    "back": "A surprise might be fine, might be fishy. Pause. Ask."
   },
   "es": {
    "front": "La voz de un video dice: “¡Suscríbete para una sorpresa!”",
    "back": "Una sorpresa puede estar bien o puede ser sospechosa. Pausa. Pregunta."
   }
  },
  {
   "id": "K55",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "An older cousin says: \"Use my account to play, here's my password!\"",
    "back": "Pause. Ask your grown-up. Passwords are not for sharing around."
   },
   "es": {
    "front": "Un primo mayor dice: “Usa mi cuenta para jugar, ¡aquí está mi contraseña!”",
    "back": "Pausa. Pregúntale a tu adulto. Las contraseñas no se comparten por ahí."
   }
  },
  {
   "id": "K56",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A chat message: \"Wow, you're good! Want to be friends?\" from a player in a game.",
    "back": "Online friends are not the same as real friends. Pause. Ask a grown-up."
   },
   "es": {
    "front": "Un mensaje en un chat: “¡Wow, juegas muy bien! ¿Quieres ser mi amigo?”, de un jugador de un juego.",
    "back": "Los amigos en línea no son lo mismo que los amigos de verdad. Pausa. Pregúntale a un adulto."
   }
  },
  {
   "id": "K57",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A chat helper says: \"I can help with homework!\"",
    "back": "Might be OK. Pause. Ask a grown-up first. A program is not a friend."
   },
   "es": {
    "front": "Un ayudante del chat dice: “¡Puedo ayudarte con la tarea!”",
    "back": "Podría estar bien. Pausa. Pregúntale primero a un adulto. Un programa no es un amigo."
   }
  },
  {
   "id": "K58",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A video shows a toy unboxing and says: \"Link below!\"",
    "back": "Pause. Ask a grown-up before any link."
   },
   "es": {
    "front": "Un video muestra cómo se abre un juguete y dice: “¡Enlace abajo!”",
    "back": "Pausa. Pregúntale a un adulto antes de tocar cualquier enlace."
   }
  },
  {
   "id": "K60",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A message has only a link and comes from a name nobody knows.",
    "back": "Pause. Do not tap. Ask a grown-up."
   },
   "es": {
    "front": "Un mensaje solo tiene un enlace y viene de un nombre que nadie conoce.",
    "back": "Pausa. No lo toques. Pregúntale a un adulto."
   }
  },
  {
   "id": "K61",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A call on the grown-up's phone says: \"This is the school.\"",
    "back": "Pause. The grown-up can call the school back on a known number."
   },
   "es": {
    "front": "Una llamada al teléfono del adulto dice: “Habla la escuela.”",
    "back": "Pausa. El adulto puede devolver la llamada a la escuela a un número conocido."
   }
  },
  {
   "id": "K62",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A grown-up wants to post a photo of you and your friends.",
    "back": "Pause. Ask: \"Do all my friends say OK?\" Pip says: share what everyone is happy to share."
   },
   "es": {
    "front": "Un adulto quiere publicar una foto tuya y de tus amigos.",
    "back": "Pausa. Pregunta: “¿Todos mis amigos dicen que sí?” Pip dice: comparte lo que a todos les parezca bien compartir."
   }
  },
  {
   "id": "K63",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend says: \"Let's swap passwords to be best friends!\"",
    "back": "Pause. Best friends do not need passwords. Tell a grown-up if the friend pushes."
   },
   "es": {
    "front": "Un amigo dice: “¡Cambiemos contraseñas para ser mejores amigos!”",
    "back": "Pausa. Los mejores amigos no necesitan contraseñas. Cuéntaselo a un adulto si tu amigo insiste."
   }
  },
  {
   "id": "K64",
   "sort": "P",
   "star": true,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The tablet says: \"Install update now?\"",
    "back": "Pause. Ask a grown-up."
   },
   "es": {
    "front": "La tableta dice: “¿Instalar la actualización ahora?”",
    "back": "Pausa. Pregúntale a un adulto."
   }
  },
  {
   "id": "K65",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A game asks: \"Use your location?\"",
    "back": "Pause. A grown-up decides. Pip says: your location is a privacy shell."
   },
   "es": {
    "front": "Un juego pregunta: “¿Usar tu ubicación?”",
    "back": "Pausa. Un adulto decide. Pip dice: tu ubicación es una concha de privacidad."
   }
  },
  {
   "id": "K66",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A kid at school says: \"I know a free-game trick. Let's try it!\"",
    "back": "Pause. Ask a grown-up first."
   },
   "es": {
    "front": "Un niño de la escuela dice: “Conozco un truco para juegos gratis. ¡Probémoslo!”",
    "back": "Pausa. Pregúntale primero a un adulto."
   }
  }
 ],
 "t": [
  {
   "id": "T1",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "L",
    "S"
   ],
   "en": {
    "front": "Text: \"Delivery notice: Your package could not be delivered. Pay a $1.99 redelivery fee at track-parcel.example/pay within 24 hours.\"",
    "back": "**F**ast, **L**ogin/payment ask, **S**trange link. If you are expecting a package, open the store's own app. **Twin:** T42."
   },
   "es": {
    "front": "Mensaje de texto: “Aviso de entrega: no pudimos entregar tu paquete. Paga una tarifa de reentrega de $1.99 en track-parcel.example/pay en 24 horas.”",
    "back": "Prisa (**F**), pago o acceso (**L**), enlace extraño (**S**). Si esperas un paquete, abre la aplicación de la tienda tú mismo. **Gemelo:** T42."
   }
  },
  {
   "id": "T2",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A",
    "L"
   ],
   "en": {
    "front": "DM: \"You won a $100 gift card in our giveaway! Confirm your username and password at claim-gift.example to receive it.\"",
    "back": "**A**mazing offer, **L**ogin ask. A prize never needs your password. Do not click. Report and delete."
   },
   "es": {
    "front": "Mensaje directo: “¡Ganaste una tarjeta de regalo de $100 en nuestro sorteo! Confirma tu usuario y tu contraseña en claim-gift.example para recibirla.”",
    "back": "Oferta asombrosa (**A**), pide acceso (**L**). Un premio nunca necesita tu contraseña. No hagas clic. Reporta y borra."
   }
  },
  {
   "id": "T3",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "L",
    "S"
   ],
   "en": {
    "front": "Email: \"Security alert: Someone logged in from another country. Verify within 1 hour or your account will be locked: secure-check.example/verify\"",
    "back": "**F**ast, **L**ogin ask, **S**trange link. Open the app yourself; check settings. **Twin:** T43."
   },
   "es": {
    "front": "Correo: “Alerta de seguridad: alguien inició sesión desde otro país. Verifica en 1 hora o bloquearemos tu cuenta: secure-check.example/verify”",
    "back": "Prisa (**F**), pide acceso (**L**), enlace extraño (**S**). Abre la aplicación tú mismo y revisa la configuración. **Gemelo:** T43."
   }
  },
  {
   "id": "T4",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "S"
   ],
   "en": {
    "front": "DM from a friend's account: \"omg is this you in this video??? pixelclip.example/watch\"",
    "back": "**S**trange link + shock bait, and not like how your friend writes. Their account may be taken over. **Check:** ask them in person."
   },
   "es": {
    "front": "Mensaje directo desde la cuenta de un amigo: “omg ¿eres tú en este video??? pixelclip.example/watch”",
    "back": "Enlace extraño (**S**) y gancho de impacto, y no suena como escribe tu amigo. Su cuenta podría estar tomada por otra persona. **Revisa:** pregúntale en persona."
   }
  },
  {
   "id": "T5",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "Ad: \"Earn $400 a day from your phone! No experience! Send a $50 starter fee.\"",
    "back": "**A**mazing offer. Real jobs do not charge you to start."
   },
   "es": {
    "front": "Anuncio: “¡Gana $400 al día desde tu teléfono! ¡Sin experiencia! Envía $50 de cuota inicial.”",
    "back": "Oferta asombrosa (**A**). Los trabajos de verdad no te cobran para empezar."
   }
  },
  {
   "id": "T6",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "S"
   ],
   "en": {
    "front": "Text: \"Hi, this is Coach, I changed my number. Can you buy 4 gift cards for the team? I'll pay you back.\"",
    "back": "**F**ast and **S**trange sender. Gift cards are a classic fishy ask. **Check:** call Coach on the number you already have."
   },
   "es": {
    "front": "Mensaje de texto: “Hola, soy el entrenador, cambié de número. ¿Puedes comprar 4 tarjetas de regalo para el equipo? Te lo devuelvo.”",
    "back": "Prisa (**F**) y remitente extraño (**S**). Las tarjetas de regalo son una petición sospechosa muy clásica. **Revisa:** llama al entrenador al número que ya tienes."
   }
  },
  {
   "id": "T7",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "L"
   ],
   "en": {
    "front": "Email: \"Your streaming account will be suspended. Update your payment now.\"",
    "back": "**F**ast, **L**ogin/payment ask. Open the service yourself; do not use the link."
   },
   "es": {
    "front": "Correo: “Tu cuenta de streaming será suspendida. Actualiza tu pago ahora.”",
    "back": "Prisa (**F**), pide pago o acceso (**L**). Abre el servicio tú mismo; no uses el enlace."
   }
  },
  {
   "id": "T8",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "Post: \"Follow, share to 10 friends, and DM your phone number to win a console!\"",
    "back": "**A**mazing offer; asks for private info. Do not share."
   },
   "es": {
    "front": "Publicación: “¡Sigue, comparte con 10 amigos y envíame tu número de teléfono por mensaje directo para ganar una consola!”",
    "back": "Oferta asombrosa (**A**); pide información privada. No la compartas."
   }
  },
  {
   "id": "T9",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "L"
   ],
   "en": {
    "front": "Text: \"Hi, I sent my verification code to you by mistake. Can you read it back to me?\"",
    "back": "**L**ogin ask. Never share a code. The code is a key to your account. **Twin:** T26."
   },
   "es": {
    "front": "Mensaje de texto: “Hola, te envié mi código de verificación por error. ¿Me lo puedes leer de vuelta?”",
    "back": "Pide acceso (**L**). Nunca compartas un código. El código es la llave de tu cuenta. **Gemelo:** T26."
   }
  },
  {
   "id": "T10",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A",
    "L"
   ],
   "en": {
    "front": "Page: \"Free VIP skin generator! No download! Just log in with your game account.\"",
    "back": "**A**mazing offer, **L**ogin ask. Skins are not free to \"generate\"."
   },
   "es": {
    "front": "Página: “¡Generador de skins VIP gratis! ¡Sin descargar nada! Solo inicia sesión con la cuenta de tu juego.”",
    "back": "Oferta asombrosa (**A**), pide acceso (**L**). Las skins no se “generan” gratis."
   }
  },
  {
   "id": "T11",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A",
    "F"
   ],
   "en": {
    "front": "Marketplace: \"Selling 2 tickets for tomorrow's big concert, half price, pay with gift cards only.\"",
    "back": "**A**mazing offer, **F**ast, odd payment. Use the official ticket site."
   },
   "es": {
    "front": "Mercado en línea: “Vendo 2 entradas para el gran concierto de mañana, a mitad de precio, solo con tarjetas de regalo.”",
    "back": "Oferta asombrosa (**A**), prisa (**F**), forma de pago rara. Usa el sitio oficial de entradas."
   }
  },
  {
   "id": "T12",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "S"
   ],
   "en": {
    "front": "School-looking email: \"The principal needs a favor. Reply with your phone number.\"",
    "back": "**S**trange sender (address is a free mail service), asks for private info. **Check:** ask a teacher in person."
   },
   "es": {
    "front": "Correo que parece de la escuela: “El director necesita un favor. Responde con tu número de teléfono.”",
    "back": "Remitente extraño (**S**; la dirección es de un servicio de correo gratis) y pide información privada. **Revisa:** pregúntale a un docente en persona."
   }
  },
  {
   "id": "T13",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F"
   ],
   "en": {
    "front": "Pop-up: \"Your computer is infected! Call 1-800-555-0101 now!\"",
    "back": "**F**ast scare. Pop-ups do not know your computer. Close the tab. Tell an adult."
   },
   "es": {
    "front": "Ventana emergente: “¡Tu computadora está infectada! ¡Llama al 1-800-555-0101 ahora!”",
    "back": "Susto con prisa (**F**). Las ventanas emergentes no conocen tu computadora. Cierra la pestaña. Cuéntaselo a un adulto."
   }
  },
  {
   "id": "T16",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "S"
   ],
   "en": {
    "front": "Browser banner: \"Your device is out of date. Download this required update now.\" from an unknown site.",
    "back": "**F**ast, **S**trange link. Updates come from your settings, not banners. **Twin:** T29."
   },
   "es": {
    "front": "Banner del navegador: “Tu dispositivo está desactualizado. Descarga esta actualización obligatoria ahora.” de un sitio desconocido.",
    "back": "Prisa (**F**), enlace extraño (**S**). Las actualizaciones vienen de tu configuración, no de banners. **Gemelo:** T29."
   }
  },
  {
   "id": "T18",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "F",
    "L"
   ],
   "en": {
    "front": "DM: \"Your photo was reported for copyright. Appeal here or your account will be deleted in 24 hours.\"",
    "back": "**F**ast, **L**ogin ask. Check your account yourself."
   },
   "es": {
    "front": "Mensaje directo: “Tu foto fue denunciada por derechos de autor. Apela aquí o tu cuenta será borrada en 24 horas.”",
    "back": "Prisa (**F**), pide acceso (**L**). Revisa tu cuenta tú mismo."
   }
  },
  {
   "id": "T19",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "Email: \"A distant relative left you $2 million. Send your bank details to receive it.\"",
    "back": "**A**mazing offer. Do not reply."
   },
   "es": {
    "front": "Correo: “Un pariente lejano te dejó $2 millones. Envía tus datos bancarios para recibirlos.”",
    "back": "Oferta asombrosa (**A**). No respondas."
   }
  },
  {
   "id": "T20",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "DM from a stranger: \"Love your art! I'll pay $200 for a commission. I'll overpay by mistake, you refund the difference.\"",
    "back": "**A**mazing, odd payment. The overpayment is the trick. Do not send money back."
   },
   "es": {
    "front": "Mensaje directo de un desconocido: “¡Me encanta tu arte! Te pago $200 por un encargo. Te pagaré de más por error y tú me devuelves la diferencia.”",
    "back": "Oferta asombrosa y forma de pago rara. El pago de más es el truco. No devuelvas dinero."
   }
  },
  {
   "id": "T21",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "L",
    "S"
   ],
   "en": {
    "front": "DM: \"Verify your age: upload a photo of your ID and a selfie to keep your account.\"",
    "back": "**L**ogin ask, **S**trange link. Real age checks happen inside the real app. Never send ID in a DM."
   },
   "es": {
    "front": "Mensaje directo: “Verifica tu edad: sube una foto de tu identificación y una selfie para conservar tu cuenta.”",
    "back": "Pide acceso (**L**), enlace extraño (**S**). Las verificaciones de edad de verdad ocurren dentro de la aplicación real. Nunca envíes una identificación por mensaje directo."
   }
  },
  {
   "id": "T22",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "Chat: \"Free crypto doubler! Send 0.1 and get 0.2 back instantly.\"",
    "back": "**A**mazing offer. [VERIFY] Nothing doubles your money."
   },
   "es": {
    "front": "Chat: “¡Duplicador de criptomonedas gratis! Envía 0.1 y recibe 0.2 al instante.”",
    "back": "Oferta asombrosa (**A**). [VERIFY] Nada duplica tu dinero."
   }
  },
  {
   "id": "T23",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A"
   ],
   "en": {
    "front": "A survey: \"Complete this survey about your school for a $50 voucher. Enter name, address, school, parent's email.\"",
    "back": "**A**mazing, private info. Ask a trusted adult."
   },
   "es": {
    "front": "Una encuesta: “Completa esta encuesta sobre tu escuela y recibe un vale de $50. Escribe nombre, dirección, escuela y correo de tu mamá o papá.”",
    "back": "Oferta asombrosa y datos privados. Pregúntale a un adulto de confianza."
   }
  },
  {
   "id": "T24",
   "sort": "F",
   "star": false,
   "heavy": false,
   "flags": [
    "A",
    "L"
   ],
   "en": {
    "front": "Email: \"Your account was selected for a lottery! Confirm your date of birth and Social Security number.\"",
    "back": "**A**mazing, **L**ogin ask. Never share ID numbers."
   },
   "es": {
    "front": "Correo: “¡Tu cuenta fue elegida para una lotería! Confirma tu fecha de nacimiento y tu número de Seguro Social.”",
    "back": "Oferta asombrosa (**A**), pide acceso (**L**). Nunca compartas números de identificación."
   }
  },
  {
   "id": "T25",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "School email from your teacher's school address: \"Assignment due Friday. See the class page.\"",
    "back": "Known sender, normal ask. Real."
   },
   "es": {
    "front": "Correo de la escuela, desde la dirección de tu docente: “La tarea es para el viernes. Mira la página de la clase.”",
    "back": "Remitente conocido, petición normal. Real."
   }
  },
  {
   "id": "T26",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "You just tried to log in; your phone shows: \"Your verification code is 482913. It expires in 10 minutes. Do not share it.\"",
    "back": "You started it. Real. **Never share** the code. **Twin:** T9."
   },
   "es": {
    "front": "Acabas de intentar iniciar sesión; tu teléfono muestra: “Tu código de verificación es 482913. Vence en 10 minutos. No lo compartas.”",
    "back": "Tú lo iniciaste. Real. **Nunca compartas** el código. **Gemelo:** T9."
   }
  },
  {
   "id": "T27",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "In the official app you opened: \"Your friend Sam posted for the first time in 2 weeks.\"",
    "back": "In-app, no ask. Real."
   },
   "es": {
    "front": "En la aplicación oficial que abriste: “Tu amigo Sam publicó por primera vez en 2 semanas.”",
    "back": "Dentro de la aplicación, no pide nada. Real."
   }
  },
  {
   "id": "T28",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Email receipt for something you just bought, with an order number you recognize.",
    "back": "Expected. Real. Check it matches."
   },
   "es": {
    "front": "Correo con el recibo de algo que acabas de comprar, con un número de pedido que reconoces.",
    "back": "Esperado. Real. Revisa que coincida."
   }
  },
  {
   "id": "T29",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "In your phone's Settings, which you opened yourself, you see: \"A software update is ready. Install tonight?\"",
    "back": "You went to Settings yourself; no rush, no link. Real. **Twin:** T16."
   },
   "es": {
    "front": "En la Configuración de tu teléfono, que abriste tú mismo, ves: “Hay una actualización de software lista. ¿Instalar esta noche?”",
    "back": "Fuiste tú a la Configuración; sin prisa y sin enlace. Real. **Gemelo:** T16."
   }
  },
  {
   "id": "T30",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A sports league newsletter you signed up for shows the weekend schedule.",
    "back": "You signed up. Real."
   },
   "es": {
    "front": "Un boletín de la liga deportiva al que te inscribiste muestra el calendario del fin de semana.",
    "back": "Te inscribiste tú. Real."
   }
  },
  {
   "id": "T31",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your parent texts: \"Can you pick up bread on the way home?\"",
    "back": "Saved contact, normal. Real."
   },
   "es": {
    "front": "Tu mamá o tu papá te escribe: “¿Puedes comprar pan de camino a casa?”",
    "back": "Contacto guardado, petición normal. Real."
   }
  },
  {
   "id": "T32",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "In the app's settings (opened by you): \"We updated our terms. View changes.\"",
    "back": "In-app and not rushed. Real. Read before agreeing."
   },
   "es": {
    "front": "En la configuración de la aplicación (abierta por ti): “Actualizamos nuestros términos. Ver cambios.”",
    "back": "Dentro de la aplicación y sin prisa. Real. Lee antes de aceptar."
   }
  },
  {
   "id": "T33",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Pharmacy text you opted into: \"Your prescription is ready.\"",
    "back": "Expected. Real."
   },
   "es": {
    "front": "Mensaje de la farmacia al que te inscribiste: “Tu receta está lista.”",
    "back": "Esperado. Real."
   }
  },
  {
   "id": "T34",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend says in person: \"I made a new account. Follow me!\" Then you see a new follower.",
    "back": "Confirmed in person. Real."
   },
   "es": {
    "front": "Un amigo te dice en persona: “Me hice una cuenta nueva. ¡Sígueme!” Luego ves un seguidor nuevo.",
    "back": "Confirmado en persona. Real."
   }
  },
  {
   "id": "T35",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Your new phone asks: \"Sign in from a new device? Yes, this was me / No.\"",
    "back": "You just got a new phone. Real."
   },
   "es": {
    "front": "Tu teléfono nuevo pregunta: “¿Iniciar sesión desde un dispositivo nuevo? Sí, fui yo / No.”",
    "back": "Acabas de conseguir un teléfono nuevo. Real."
   }
  },
  {
   "id": "T36",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "The coach's team chat: \"Practice is canceled due to rain.\"",
    "back": "Known chat. Real."
   },
   "es": {
    "front": "El chat del equipo del entrenador: “Se cancela la práctica por lluvia.”",
    "back": "Chat conocido. Real."
   }
  },
  {
   "id": "T37",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Email from the college you applied to: \"We have received your application.\"",
    "back": "You applied. Real."
   },
   "es": {
    "front": "Correo de la universidad a la que aplicaste: “Recibimos tu solicitud.”",
    "back": "Tú aplicaste. Real."
   }
  },
  {
   "id": "T38",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Official app: \"Your plan renews on the 14th.\"",
    "back": "In-app, no ask. Real."
   },
   "es": {
    "front": "Aplicación oficial: “Tu plan se renueva el día 14.”",
    "back": "Dentro de la aplicación, no pide nada. Real."
   }
  },
  {
   "id": "T39",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Repair shop text: \"Your phone repair is complete.\"",
    "back": "You dropped it off. Real."
   },
   "es": {
    "front": "Mensaje del taller de reparación: “La reparación de tu teléfono está lista.”",
    "back": "Lo dejaste tú. Real."
   }
  },
  {
   "id": "T40",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A teacher shares a link on the class page you opened yourself.",
    "back": "Known source. Real."
   },
   "es": {
    "front": "Un docente comparte un enlace en la página de la clase que abriste tú mismo.",
    "back": "Fuente conocida. Real."
   }
  },
  {
   "id": "T41",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend texts: \"Call me when you're free, I want to ask something.\"",
    "back": "No link, no pressure, sounds like them. Real. **Twin:** T6."
   },
   "es": {
    "front": "Un amigo te escribe: “Llámame cuando puedas, quiero preguntarte algo.”",
    "back": "Sin enlace, sin presión, suena como esa persona. Real. **Gemelo:** T6."
   }
  },
  {
   "id": "T42",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "You ordered a book. The store's own app says: \"Your order shipped\" with tracking.",
    "back": "You started it. Real. **Twin:** T1."
   },
   "es": {
    "front": "Pediste un libro. La aplicación de la tienda dice: “Tu pedido fue enviado”, con seguimiento.",
    "back": "Tú lo iniciaste. Real. **Gemelo:** T1."
   }
  },
  {
   "id": "T43",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "You open the real app and see: \"New sign-in from a laptop. Was this you?\" You review it inside the app.",
    "back": "You went to the app yourself. Real. **Twin:** T3."
   },
   "es": {
    "front": "Abres la aplicación de verdad y ves: “Nuevo inicio de sesión desde una laptop. ¿Fuiste tú?” Lo revisas dentro de la aplicación.",
    "back": "Fuiste tú a la aplicación. Real. **Gemelo:** T3."
   }
  },
  {
   "id": "T44",
   "sort": "R",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A relative says: \"Remember our Family Code Word: banana.\"",
    "back": "You set it up with your family, in person. Real. **Note:** \"banana\" is only an example and now everyone has heard it. Real families pick their own word and never say it in public or type it in a chat."
   },
   "es": {
    "front": "Un familiar dice: “Recuerda la palabra clave de nuestra familia: banana.”",
    "back": "Lo acordaste con tu familia, en persona. Real. **Nota:** “banana” es solo un ejemplo y ya todos la oyeron. Las familias de verdad eligen su propia palabra y nunca la dicen en público ni la escriben en un chat."
   }
  },
  {
   "id": "T46",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A QR sticker on a hallway poster says: \"Scan for free pizza on Friday.\"",
    "back": "A sticker can cover a real poster. **Check:** ask staff."
   },
   "es": {
    "front": "Un adhesivo con código QR en un cartel del pasillo dice: “Escanea para pizza gratis el viernes.”",
    "back": "Un adhesivo puede tapar un cartel de verdad. **Revisa:** pregúntale al personal."
   }
  },
  {
   "id": "T47",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Email \"from School IT\": \"Your password expires today. Go to the school portal.\" (no link)",
    "back": "Plausible, but pressured. **Check:** type the portal address yourself; ask IT in person."
   },
   "es": {
    "front": "Correo “de Informática de la escuela”: “Tu contraseña vence hoy. Ve al portal de la escuela.” (sin enlace)",
    "back": "Es creíble, pero trae presión. **Revisa:** escribe tú mismo la dirección del portal; pregúntale a Informática en persona."
   }
  },
  {
   "id": "T48",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend sends just a link, no words.",
    "back": "**Check:** ask them in person. Their account might have been taken over."
   },
   "es": {
    "front": "Un amigo te manda solo un enlace, sin palabras.",
    "back": "**Revisa:** pregúntale en persona. Su cuenta podría haber sido tomada por otra persona."
   }
  },
  {
   "id": "T49",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A site asks: \"Allow notifications?\"",
    "back": "Usually choose No. Pause and check what it is for."
   },
   "es": {
    "front": "Un sitio pregunta: “¿Permitir notificaciones?”",
    "back": "Normalmente elige No. Pausa y revisa para qué sirve."
   }
  },
  {
   "id": "T50",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "An online store has a price 70% lower than anyone else's.",
    "back": "**Check:** search the seller name and reviews from another source."
   },
   "es": {
    "front": "Una tienda en línea tiene un precio 70% más bajo que todas las demás.",
    "back": "**Revisa:** busca al vendedor y sus reseñas en otra fuente."
   }
  },
  {
   "id": "T51",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "An app asks for your contacts and microphone \"to work properly.\"",
    "back": "Pause. Do you need it? Footprint check: only allow what is needed."
   },
   "es": {
    "front": "Una aplicación pide tus contactos y tu micrófono “para funcionar bien”.",
    "back": "Pausa. ¿Lo necesitas? Revisión de huella: permite solo lo necesario."
   }
  },
  {
   "id": "T52",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A \"brand ambassador\" DM: \"We'd love to send you free gear. Fill in this form with your address.\"",
    "back": "Maybe real, maybe a data grab. **Check:** go to the brand's official site yourself."
   },
   "es": {
    "front": "Un mensaje directo de “embajador de marca”: “Nos encantaría enviarte equipo gratis. Llena este formulario con tu dirección.”",
    "back": "Quizás sea real, quizás sea una toma de datos. **Revisa:** entra tú mismo al sitio oficial de la marca."
   }
  },
  {
   "id": "T53",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A widely shared photo shows a famous landmark flooded.",
    "back": "**Check:** lateral read (open new tabs: do trusted news outlets show it?)."
   },
   "es": {
    "front": "Una foto muy compartida muestra un monumento famoso inundado.",
    "back": "**Revisa:** lectura lateral (abre pestañas nuevas: ¿los medios de confianza lo muestran?)."
   }
  },
  {
   "id": "T54",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A voice note \"from the principal\" says: \"School closed tomorrow.\"",
    "back": "**Check:** the school's official channel. Voices can be faked [VERIFY]."
   },
   "es": {
    "front": "Una nota de voz “del director” dice: “Mañana no hay clases.”",
    "back": "**Revisa:** el canal oficial de la escuela. Las voces se pueden falsificar [VERIFY]."
   }
  },
  {
   "id": "T55",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A friend's video: \"Try this new AI app!\" It needs you to upload your photo.",
    "back": "Pause. Read what happens to the photo. Privacy first."
   },
   "es": {
    "front": "El video de un amigo: “¡Prueba esta nueva aplicación de IA!” Necesita que subas tu foto.",
    "back": "Pausa. Lee qué pasa con la foto. Primero la privacidad."
   }
  },
  {
   "id": "T56",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A quiz: \"Which celebrity are you?\" asks you to \"Log in with your account.\"",
    "back": "Pause. Logging in with an account gives the quiz access. Check what it can see."
   },
   "es": {
    "front": "Un cuestionario: “¿Qué celebridad eres?” te pide “Iniciar sesión con tu cuenta”.",
    "back": "Pausa. Iniciar sesión con tu cuenta le da acceso al cuestionario. Revisa qué puede ver."
   }
  },
  {
   "id": "T57",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Group chat: \"Anyone want to try this trading bot? Made me $500!\"",
    "back": "**Check:** who said it, does anyone verify? Likely fishy, but check."
   },
   "es": {
    "front": "Chat de grupo: “¿Alguien quiere probar este bot de inversiones? ¡Me hizo ganar $500!”",
    "back": "**Revisa:** ¿quién lo dijo? ¿Alguien lo comprueba? Probablemente es sospechoso, pero revisa."
   }
  },
  {
   "id": "T58",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A pop-up on a free-video site says: \"Your player is out of date.\"",
    "back": "Do not click. Close the tab. Pause."
   },
   "es": {
    "front": "Una ventana emergente en un sitio de videos gratis dice: “Tu reproductor está desactualizado.”",
    "back": "No hagas clic. Cierra la pestaña. Pausa."
   }
  },
  {
   "id": "T59",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A new account with 3 posts and 9,000 followers likes all your pictures.",
    "back": "Pause. Could be a bot; do not DM; check the profile."
   },
   "es": {
    "front": "Una cuenta nueva con 3 publicaciones y 9,000 seguidores le da me gusta a todas tus fotos.",
    "back": "Pausa. Podría ser un bot; no le escribas; revisa el perfil."
   }
  },
  {
   "id": "T60",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "Email: \"You've been selected for a summer program!\" You did not apply.",
    "back": "**Check:** the program's official website. Ask a trusted adult."
   },
   "es": {
    "front": "Correo: “¡Fuiste elegido para un programa de verano!” No solicitaste nada.",
    "back": "**Revisa:** el sitio web oficial del programa. Pregúntale a un adulto de confianza."
   }
  },
  {
   "id": "T63",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A classmate asks: \"Can I borrow your login for just a minute?\"",
    "back": "Pause. The answer is no, kindly. \"Let me do it for you.\""
   },
   "es": {
    "front": "Un compañero pregunta: “¿Me prestas tu usuario y contraseña solo un minuto?”",
    "back": "Pausa. La respuesta es no, con amabilidad. “Mejor lo hago yo por ti.”"
   }
  },
  {
   "id": "T64",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A message: \"Group admin: Everyone verify your account at the link or you'll be removed.\"",
    "back": "Pause. **Check:** ask the admin in person."
   },
   "es": {
    "front": "Un mensaje: “Administrador del grupo: todos deben verificar su cuenta en el enlace o los sacaremos.”",
    "back": "Pausa. **Revisa:** pregúntale al administrador en persona."
   }
  },
  {
   "id": "T65",
   "sort": "P",
   "star": false,
   "heavy": false,
   "flags": [],
   "en": {
    "front": "A \"free\" trial wants your payment info and says \"cancel anytime.\"",
    "back": "Pause. **Check:** terms, who pays, ask a trusted adult."
   },
   "es": {
    "front": "Una prueba “gratis” pide tus datos de pago y dice “cancela cuando quieras”.",
    "back": "Pausa. **Revisa:** los términos, quién paga, y pregúntale a un adulto de confianza."
   }
  }
 ],
 "twins": [
  {
   "fishy": "T1",
   "real": "T42",
   "diff": "You started the order; the real one is in the store's app.",
   "diffEs": "Tú empezaste el pedido; el aviso real está en la aplicación de la tienda."
  },
  {
   "fishy": "T3",
   "real": "T43",
   "diff": "You went to the app yourself; no timer.",
   "diffEs": "Fuiste tú a la aplicación; no había cuenta regresiva."
  },
  {
   "fishy": "T9",
   "real": "T26",
   "diff": "You started it; real codes are never to be shared.",
   "diffEs": "Tú lo iniciaste; los códigos de verdad nunca se comparten."
  },
  {
   "fishy": "T6",
   "real": "T41",
   "diff": "Real asks have no money, no pressure, no secrecy.",
   "diffEs": "Las peticiones reales no traen dinero, ni presión, ni secretos."
  },
  {
   "fishy": "T7",
   "real": "T38",
   "diff": "Real notices inside the app need no action in a hurry.",
   "diffEs": "Los avisos reales dentro de la aplicación no piden actuar con prisa."
  },
  {
   "fishy": "T12",
   "real": "T25",
   "diff": "Known address and a normal ask.",
   "diffEs": "Dirección conocida y una petición normal."
  },
  {
   "fishy": "T18",
   "real": "T32",
   "diff": "Real ones are in the app and not threats.",
   "diffEs": "Los reales están en la aplicación y no son amenazas."
  },
  {
   "fishy": "T21",
   "real": "T35",
   "diff": "Real steps happen inside the app.",
   "diffEs": "Los pasos reales ocurren dentro de la aplicación."
  },
  {
   "fishy": "T24",
   "real": "T37",
   "diff": "You applied.",
   "diffEs": "Tú solicitaste."
  },
  {
   "fishy": "T4",
   "real": "T34",
   "diff": "You confirmed in person.",
   "diffEs": "Lo confirmaste en persona."
  },
  {
   "fishy": "T16",
   "real": "T29",
   "diff": "Real updates come from your own settings or the official store, not a banner.",
   "diffEs": "Las actualizaciones reales vienen de tu propia configuración o de la tienda oficial, no de un banner."
  }
 ],
 "quick": {
  "k5": [
   "K1",
   "K6",
   "K19",
   "K23",
   "K27",
   "K31",
   "K45",
   "K49"
  ],
  "t": [
   "T2",
   "T9",
   "T13",
   "T26",
   "T36",
   "T42",
   "T46",
   "T48"
  ]
 },
 "meta": {
  "k5Total": 66,
  "tTotal": 66,
  "excluded": {
   "K9": "stranger asks where you live (deck says skip with easily upset children)",
   "K14": "private room plus a secret from a stranger (grooming pattern)",
   "K59": "stranger asks how old you are (deck says skip with easily upset children)",
   "T14": "online friend asks to move to a private app and keep it secret (grooming pattern)",
   "T15": "(H) threat to leak private chats",
   "T17": "(H) cloned voice asks for secret money",
   "T45": "move to another app after meeting online (grooming pattern)",
   "T61": "stranger gifts as a way in (grooming pattern)",
   "T62": "(H) screenshot meant to hurt a teacher",
   "T66": "(H) mean post about a classmate's photo"
  }
 }
};
