/* Spot the Fishy: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "spot.title": "Spot the Fishy",
    "spot.kicker": "Plate 1 of 6",
    "spot.lead": "Read a short message. Decide if it is Fishy, Real, or needs Pause and Ask. The whole class is one team and nobody is out.",
    "spot.how": "How it works",
    "spot.how1": "You read a card. Think for a moment.",
    "spot.how2": "Pick Fishy, Real, or Pause and Ask. All three are allowed. Pause and Ask is a hero move.",
    "spot.how3": "You see what the deck says and why. Every card fills the Pond.",
    "spot.deck": "Which deck?",
    "spot.deck.k5": "K-5 deck (ages 5 to 10)",
    "spot.deck.t": "6-12 deck (ages 11 to 18)",
    "spot.stars": "Only the K-2 star cards (short, good to read aloud)",
    "spot.who": "Who is playing?",
    "spot.who.solo": "One person or a pair on this screen",
    "spot.who.team": "A class in teams (one screen, the teacher runs it)",
    "spot.teams": "How many teams?",
    "spot.teamsNote": "Teams get a crew name. Nobody types anything.",
    "spot.length": "How long?",
    "spot.len.quick": "10 minutes: Quick Catch (8 cards, Mini Pond of 12 circles)",
    "spot.len.full": "30 minutes: Full Pond (24 cards in 3 rounds, Pond of 30 plus Lagoon of 24)",
    "spot.teacher": "Teacher options",
    "spot.timer": "Think timer",
    "spot.timer.off": "Off (the default)",
    "spot.timer.10": "10 seconds",
    "spot.timer.20": "20 seconds",
    "spot.timer.30": "30 seconds",
    "spot.timerNote": "The timer is a calm bar. Nothing happens when it ends. Leave it off if time pressure bothers anyone.",
    "spot.clues": "Name the flag bonus",
    "spot.clues.on": "On: players can name a clue for an extra Pond circle",
    "spot.clues.off": "Off: just sort the cards",
    "spot.start": "Start the game",
    "spot.privacyNote": "All cards are invented. Links end in .example, which is pretend. No names, no typing, nothing saved.",

    "spot.card": "Card {n} of {total}",
    "spot.round": "Round {r} of 3: {name}",
    "spot.round.1": "Notice",
    "spot.round.2": "Name",
    "spot.round.3": "Move",
    "spot.round.quick": "Quick Catch",
    "spot.roundHint.1": "Just sort the card.",
    "spot.roundHint.2": "After you sort, name one clue you noticed. Each new clue adds a circle.",
    "spot.roundHint.3": "After you sort, act out the next step (see the Move box).",
    "spot.pond": "The Pond",
    "spot.pondMini": "Mini Pond",
    "spot.pondCount": "{n} of {goal} circles filled",
    "spot.row.shore": "Shore",
    "spot.row.shallows": "Shallows",
    "spot.row.deep": "Deep",
    "spot.row.lagoon1": "Lagoon, row 1",
    "spot.row.lagoon2": "Lagoon, row 2",
    "spot.row.mini": "Mini Pond",
    "spot.reading": "Read this card",
    "spot.pickPrompt": "What do you think? Pick one.",
    "spot.teamPick": "Each team picks an answer. Then the teacher says \"Peek!\"",
    "spot.team": "Team {name}",
    "spot.teamReady": "ready",
    "spot.teamNotYet": "thinking",
    "spot.peek": "Peek! Show all answers",
    "spot.peekHelp": "Answers stay hidden until Peek.",
    "spot.waiting": "Waiting for every team to pick. Answers stay hidden until Peek.",
    "spot.pass": "Pass, please",
    "spot.passNote": "Pass is always fine. No questions asked.",
    "spot.askBuddy": "Ask Buddy (once per game)",
    "spot.askBuddyUsed": "Ask Buddy was used",
    "spot.buddyHint": "Buddy says: think about",
    "spot.buddyHintNone": "Buddy says: can you tell who this is from? Did you start it yourself? If you cannot tell, Pause and Ask is the move.",
    "spot.keys": "Shortcut keys: 1 Fishy, 2 Real, 3 Pause and Ask, N next card.",
    "spot.timerLabel": "Think time",
    "spot.timerDone": "Peek when you are ready.",
    "spot.timerSec": "{n} seconds",
    "spot.pause": "Pause the timer",
    "spot.resume": "Resume the timer",

    "spot.s.F": "Fishy",
    "spot.s.R": "Real",
    "spot.s.P": "Pause and Ask",
    "spot.bucket.F": "FISHY",
    "spot.bucket.R": "REAL",
    "spot.bucket.P": "PAUSE AND ASK",
    "spot.what.F": "My hackles are up. I think this is a trick.",
    "spot.what.R": "Looks safe. I know who it is from and I expected it.",
    "spot.what.P": "I can't tell. I will check another way or ask a trusted adult.",
    "spot.yourPick": "your pick",
    "spot.answer": "answer",

    "spot.revealIs": "This card is: {sort}",
    "spot.revealTeams": "{best} of {teams} teams showed the best answer. Every team keeps going together.",
    "spot.revealCounts": "Teams showed: Fishy {F}, Real {R}, Pause and Ask {P}, Pass {X}",
    "spot.nice": "Nice noticing!",
    "spot.out.match_F": "Great spotting. Your hackles were right.",
    "spot.out.match_R": "Good gut check. This one is safe, and you saw why.",
    "spot.out.match_P": "You spotted the \"can't tell\". Pause and Ask is the hero move.",
    "spot.out.pause_safe": "Pause and Ask is always a safe move. To make it extra strong, name one way to check.",
    "spot.out.cant_tell": "Tricky one! You can't tell from the message alone. That is why Pause and Ask is the hero move here.",
    "spot.out.false_alarm": "A false alarm is fine! Your hackles did a great check. Here is why this one is real.",
    "spot.out.looked_real": "Good try. Fishy things often look real. Here is the clue to spot next time.",
    "spot.out.pass": "Pass is always fine. Here is what this card is about.",
    "spot.checkIdeas": "Ways to check: open the app myself, call the number I already have, ask in person, or ask a trusted adult.",
    "spot.deckSays": "What the deck says",
    "spot.pondEarned": "Pond circles for this card: {n}",
    "spot.pe.always": "1 for playing the card",
    "spot.pe.half": "1 because at least half of the teams showed the best answer",
    "spot.pe.clues": "{n} for naming clues",
    "spot.pe.soloHalf": "1 for the best answer",
    "spot.cheer.10": "Peeper's Cheer! Everyone does Hackles Up and shouts \"Spot it!\"",
    "spot.cheer.20": "Hackle's Wave! Everyone does the Tell Wave.",
    "spot.cheer.30": "You Spotted Me! The Pond is full. Gifty the Too-Good Box wears a party hat.",
    "spot.cheer.12": "The Mini Pond is full. You spotted it together!",

    "spot.nameFlag": "Name the flag (bonus)",
    "spot.nameFlagHelp": "Which clue did you notice? Pick up to two. Each right one adds a Pond circle.",
    "spot.nameFlagTeam": "A team says one clue out loud. The teacher taps it here. Up to two count.",
    "spot.clueYes": "Yes, that clue is in this card. +1 circle.",
    "spot.clueNo": "That clue is not in this card. Good looking anyway. No circle lost.",
    "spot.noFlags": "This card has no clue letters. Real things can look a little like fishy ones. The difference is whether you started it and whether it rushes you.",
    "spot.spot.S": "Secret",
    "spot.spot.P": "Pressure",
    "spot.spot.O": "Offer too good",
    "spot.spot.T": "Trick to move you",
    "spot.flags.F": "Fast (rush or threat)",
    "spot.flags.L": "Login ask (password, code, account info)",
    "spot.flags.A": "Amazing offer",
    "spot.flags.G": "Gotta keep it secret",
    "spot.flags.S": "Strange sender or link",
    "spot.legend.k5": "SPOT clues",
    "spot.legend.t": "FLAGS clues",

    "spot.move": "The Hackles move (5 seconds)",
    "spot.move.body": "Everyone does it together: Hackles Up (hand brushed up the back of the neck), Pause Palm, Check Eyes, Tell Wave. Then say: Hackles up? Pause. Check. Tell.",
    "spot.move3.k5": "Round 3: one team acts out the next step for 5 seconds. A Pause Palm and a Tell Wave is enough. Nobody acts out the sneaky part.",
    "spot.move3.t": "Round 3: one team says the one-sentence Tell script: \"Something is going on and I need help figuring out what to do. Can I show you?\"",
    "spot.twin": "Twin card",
    "spot.twinShow": "Show the twin",
    "spot.twinHide": "Hide the twin",
    "spot.twinSays": "The twin of this card is {id}. What is different?",
    "spot.twinDiff": "The difference: ",
    "spot.next": "Next card",
    "spot.finish": "See the Pond",

    "spot.end.title": "The class filled the Pond together",
    "spot.end.sub": "You sorted {n} cards and named {c} clues.",
    "spot.end.boost": "Peeper's Boost: Peeper added {n} circles so the whole pond is full. The class cannot lose.",
    "spot.end.full": "The Pond is full. Nice noticing, everyone.",
    "spot.end.pause": "Peeper's Pause: pick one thing you will remember.",
    "spot.rem.1": "Hackles up is a good feeling to notice. A false alarm is fine.",
    "spot.rem.2": "Pause and Ask is always a safe move.",
    "spot.rem.3": "Check another way: open the app myself, call a number I already have.",
    "spot.rem.4": "Tell a trusted adult. It is never my fault.",
    "spot.rem.picked": "Good one to remember: {t}",
    "spot.chant": "Hackles up? Pause. Check. Tell.",
    "spot.again": "Play again",
    "spot.lab": "Back to Lab home",
    "spot.teacherNote": "Teacher: after the game, ask \"What did you do to check?\" and list the second channels the class names.",
    "spot.liveCard": "Card {n} of {total}. {text}",
    "spot.liveReveal": "{sort}. {out} Pond: {have} of {goal}.",
    "spot.liveTimer": "Think time is over. Peek when you are ready.",
    "spot.liveStart": "Game started. {deck}.",
    "spot.newGame": "New game",
    "spot.change": "Change"
  },
  es: {
    "spot.title": "Detecta lo Sospechoso",
    "spot.kicker": "Lámina 1 de 6",
    "spot.lead": "Lee un mensaje corto. Decide si es Sospechoso, Real o si necesita Pausa y Pregunta. Toda la clase es un solo equipo y nadie queda fuera.",
    "spot.how": "Cómo funciona",
    "spot.how1": "Lees una tarjeta. Piensa un momento.",
    "spot.how2": "Elige Sospechoso, Real o Pausa y Pregunta. Las tres se valen. Pausa y Pregunta es una jugada heroica.",
    "spot.how3": "Ves lo que dice el mazo y por qué. Cada tarjeta llena el Estanque.",
    "spot.deck": "¿Qué mazo?",
    "spot.deck.k5": "Mazo K-5 (de 5 a 10 años)",
    "spot.deck.t": "Mazo 6-12 (de 11 a 18 años)",
    "spot.stars": "Solo las tarjetas con estrella de K-2 (cortas, buenas para leer en voz alta)",
    "spot.who": "¿Quién juega?",
    "spot.who.solo": "Una persona o una pareja en esta pantalla",
    "spot.who.team": "Una clase en equipos (una pantalla, la dirige el docente)",
    "spot.teams": "¿Cuántos equipos?",
    "spot.teamsNote": "Los equipos reciben un nombre de la tripulación. Nadie escribe nada.",
    "spot.length": "¿Cuánto tiempo?",
    "spot.len.quick": "10 minutos: Pesca Rápida (8 tarjetas, Mini Estanque de 12 círculos)",
    "spot.len.full": "30 minutos: Estanque Completo (24 tarjetas en 3 rondas, Estanque de 30 y Laguna de 24)",
    "spot.teacher": "Opciones para docentes",
    "spot.timer": "Temporizador para pensar",
    "spot.timer.off": "Apagado (lo normal)",
    "spot.timer.10": "10 segundos",
    "spot.timer.20": "20 segundos",
    "spot.timer.30": "30 segundos",
    "spot.timerNote": "El temporizador es una barra tranquila. No pasa nada cuando termina. Déjalo apagado si la presión del tiempo molesta a alguien.",
    "spot.clues": "Bono de nombrar la pista",
    "spot.clues.on": "Sí: se puede nombrar una pista para ganar un círculo extra en el Estanque",
    "spot.clues.off": "No: solo clasificar las tarjetas",
    "spot.start": "Empezar el juego",
    "spot.privacyNote": "Todas las tarjetas son inventadas. Los enlaces terminan en .example, que es de mentira. Sin nombres, sin escribir, sin guardar nada.",

    "spot.card": "Tarjeta {n} de {total}",
    "spot.round": "Ronda {r} de 3: {name}",
    "spot.round.1": "Notar",
    "spot.round.2": "Nombrar",
    "spot.round.3": "Moverse",
    "spot.round.quick": "Pesca Rápida",
    "spot.roundHint.1": "Solo clasifica la tarjeta.",
    "spot.roundHint.2": "Después de clasificar, nombra una pista que notaste. Cada pista nueva suma un círculo.",
    "spot.roundHint.3": "Después de clasificar, representa el siguiente paso (mira el cuadro Moverse).",
    "spot.pond": "El Estanque",
    "spot.pondMini": "Mini Estanque",
    "spot.pondCount": "{n} de {goal} círculos llenos",
    "spot.row.shore": "Orilla",
    "spot.row.shallows": "Aguas poco profundas",
    "spot.row.deep": "Aguas profundas",
    "spot.row.lagoon1": "Laguna, fila 1",
    "spot.row.lagoon2": "Laguna, fila 2",
    "spot.row.mini": "Mini Estanque",
    "spot.reading": "Lee esta tarjeta",
    "spot.pickPrompt": "¿Qué piensas? Elige una.",
    "spot.teamPick": "Cada equipo elige una respuesta. Luego el docente dice “¡Peek!”",
    "spot.team": "Equipo {name}",
    "spot.teamReady": "listo",
    "spot.teamNotYet": "pensando",
    "spot.peek": "¡Peek! Mostrar todas las respuestas",
    "spot.peekHelp": "Las respuestas quedan ocultas hasta el Peek.",
    "spot.waiting": "Esperando que cada equipo elija. Las respuestas quedan ocultas hasta el Peek.",
    "spot.pass": "Paso, por favor",
    "spot.passNote": "Pasar siempre está bien. Sin preguntas.",
    "spot.askBuddy": "Pregunta a Buddy (una vez por juego)",
    "spot.askBuddyUsed": "Ya usaste Pregunta a Buddy",
    "spot.buddyHint": "Buddy dice: piensa en",
    "spot.buddyHintNone": "Buddy dice: ¿puedes saber de quién viene? ¿Lo empezaste tú? Si no puedes saberlo, Pausa y Pregunta es la jugada.",
    "spot.keys": "Teclas rápidas: 1 Sospechoso, 2 Real, 3 Pausa y Pregunta, N siguiente tarjeta.",
    "spot.timerLabel": "Tiempo para pensar",
    "spot.timerDone": "Haz Peek cuando estés listo.",
    "spot.timerSec": "{n} segundos",
    "spot.pause": "Pausar el temporizador",
    "spot.resume": "Reanudar el temporizador",

    "spot.s.F": "Sospechoso",
    "spot.s.R": "Real",
    "spot.s.P": "Pausa y Pregunta",
    "spot.bucket.F": "SOSPECHOSO",
    "spot.bucket.R": "REAL",
    "spot.bucket.P": "PAUSA Y PREGUNTA",
    "spot.what.F": "Se me eriza la piel. Creo que es un truco.",
    "spot.what.R": "Parece seguro. Sé de quién viene y lo esperaba.",
    "spot.what.P": "No puedo saberlo. Revisaré de otra manera o le preguntaré a un adulto de confianza.",
    "spot.yourPick": "tu elección",
    "spot.answer": "respuesta",

    "spot.revealIs": "Esta tarjeta es: {sort}",
    "spot.revealTeams": "{best} de {teams} equipos mostraron la mejor respuesta. Todos los equipos siguen juntos.",
    "spot.revealCounts": "Los equipos mostraron: Sospechoso {F}, Real {R}, Pausa y Pregunta {P}, Paso {X}",
    "spot.nice": "¡Buen ojo!",
    "spot.out.match_F": "Muy bien detectado. Tu corazonada tenía razón.",
    "spot.out.match_R": "Buena corazonada. Esta es segura, y viste por qué.",
    "spot.out.match_P": "Notaste el “no puedo saberlo”. Pausa y Pregunta es la jugada heroica.",
    "spot.out.pause_safe": "Pausa y Pregunta siempre es una jugada segura. Para hacerla más fuerte, nombra una forma de revisar.",
    "spot.out.cant_tell": "¡Esta es difícil! No se puede saber solo con el mensaje. Por eso Pausa y Pregunta es la jugada heroica aquí.",
    "spot.out.false_alarm": "¡Una falsa alarma está bien! Tu corazonada hizo una buena revisión. Mira por qué esta es real.",
    "spot.out.looked_real": "Buen intento. Lo sospechoso muchas veces parece real. Esta es la pista para notar la próxima vez.",
    "spot.out.pass": "Pasar siempre está bien. Esto es de lo que trata esta tarjeta.",
    "spot.checkIdeas": "Formas de revisar: abrir la aplicación yo mismo, llamar al número que ya tengo, preguntar en persona o preguntarle a un adulto de confianza.",
    "spot.deckSays": "Lo que dice el mazo",
    "spot.pondEarned": "Círculos del Estanque por esta tarjeta: {n}",
    "spot.pe.always": "1 por jugar la tarjeta",
    "spot.pe.half": "1 porque al menos la mitad de los equipos mostró la mejor respuesta",
    "spot.pe.clues": "{n} por nombrar pistas",
    "spot.pe.soloHalf": "1 por la mejor respuesta",
    "spot.cheer.10": "¡Ovación de Peeper! Todos hacen Piel erizada y gritan “¡Lo detecté!”",
    "spot.cheer.20": "¡Saludo de Hackle! Todos hacen la Mano que Cuenta.",
    "spot.cheer.30": "¡Me Detectaron! El Estanque está lleno. Gifty, la Caja Demasiado Buena, se pone un sombrero de fiesta.",
    "spot.cheer.12": "El Mini Estanque está lleno. ¡Lo detectaron juntos!",

    "spot.nameFlag": "Nombra la pista (bono)",
    "spot.nameFlagHelp": "¿Qué pista notaste? Elige hasta dos. Cada acierto suma un círculo.",
    "spot.nameFlagTeam": "Un equipo dice una pista en voz alta. El docente la toca aquí. Cuentan hasta dos.",
    "spot.clueYes": "Sí, esa pista está en esta tarjeta. +1 círculo.",
    "spot.clueNo": "No está en esta tarjeta, pero buen ojo. No se pierde ningún círculo.",
    "spot.noFlags": "Esta tarjeta no tiene letras de pista. Lo real a veces se parece un poco a lo sospechoso. La diferencia es si tú lo empezaste y si te mete prisa.",
    "spot.spot.S": "Secreto",
    "spot.spot.P": "Presión",
    "spot.spot.O": "Oferta demasiado buena",
    "spot.spot.T": "Truco para hacerte actuar",
    "spot.flags.F": "Prisa (apuro o amenaza)",
    "spot.flags.L": "Pide acceso (contraseña, código, datos de la cuenta)",
    "spot.flags.A": "Oferta asombrosa",
    "spot.flags.G": "Hay que guardarlo en secreto",
    "spot.flags.S": "Remitente o enlace extraño",
    "spot.legend.k5": "Pistas SPOT",
    "spot.legend.t": "Pistas FLAGS",

    "spot.move": "El movimiento de Hackles (5 segundos)",
    "spot.move.body": "Todos lo hacen juntos: Piel erizada (la mano sube por la nuca), Palma de Pausa, Ojos que Revisan, Mano que Cuenta. Luego digan: ¿Se te eriza la piel? Pausa. Revisa. Cuenta.",
    "spot.move3.k5": "Ronda 3: un equipo representa el siguiente paso durante 5 segundos. Basta una Palma de Pausa y una Mano que Cuenta. Nadie representa la parte tramposa.",
    "spot.move3.t": "Ronda 3: un equipo dice la frase de Cuenta en una oración: “Está pasando algo y necesito ayuda para saber qué hacer. ¿Puedo mostrártelo?”",
    "spot.twin": "Tarjeta gemela",
    "spot.twinShow": "Mostrar la gemela",
    "spot.twinHide": "Ocultar la gemela",
    "spot.twinSays": "La gemela de esta tarjeta es {id}. ¿Qué es diferente?",
    "spot.twinDiff": "La diferencia: ",
    "spot.next": "Siguiente tarjeta",
    "spot.finish": "Ver el Estanque",

    "spot.end.title": "La clase llenó el Estanque junta",
    "spot.end.sub": "Clasificaron {n} tarjetas y nombraron {c} pistas.",
    "spot.end.boost": "Impulso de Peeper: Peeper añadió {n} círculos para que todo el estanque quedara lleno. La clase no puede perder.",
    "spot.end.full": "El Estanque está lleno. Buen ojo, todos.",
    "spot.end.pause": "Pausa de Peeper: elige algo que vas a recordar.",
    "spot.rem.1": "Se me eriza la piel es una sensación buena para notar. Una falsa alarma está bien.",
    "spot.rem.2": "Pausa y Pregunta siempre es una jugada segura.",
    "spot.rem.3": "Revisa de otra manera: abrir la aplicación yo mismo, llamar a un número que ya tengo.",
    "spot.rem.4": "Cuéntaselo a un adulto de confianza. Nunca es mi culpa.",
    "spot.rem.picked": "Buena para recordar: {t}",
    "spot.chant": "¿Se te eriza la piel? Pausa. Revisa. Cuenta.",
    "spot.again": "Jugar otra vez",
    "spot.lab": "Volver al inicio del Laboratorio",
    "spot.teacherNote": "Docente: después del juego, pregunta “¿Qué hiciste para revisar?” y anota los segundos canales que nombre la clase.",
    "spot.liveCard": "Tarjeta {n} de {total}. {text}",
    "spot.liveReveal": "{sort}. {out} Estanque: {have} de {goal}.",
    "spot.liveTimer": "Se acabó el tiempo para pensar. Haz Peek cuando estés listo.",
    "spot.liveStart": "Empezó el juego. {deck}.",
    "spot.newGame": "Juego nuevo",
    "spot.change": "Cambiar"
  }
});
