/* Generated by _build/build_data.py from the kit's Markdown. Do not edit by hand. */
window.HK_DATA = window.HK_DATA || {};
window.HK_DATA.trail = {
 "events": [
  {
   "id": "E1",
   "zone": 1,
   "best": "C",
   "ok": "B",
   "oops": "A",
   "en": {
    "situation": "Maya is playing a game on the family tablet. A pop-up says \"WIN A PONY! TAP NOW!\" Her dad is cooking in the kitchen. What does Maya do?",
    "A": "Tap it to see.",
    "B": "Close the tablet and say nothing.",
    "C": "Hackles up! Pause Palm, then walk to Dad and tell.",
    "reasons": {
     "best": "Pause, Tell",
     "ok": "safe, but Dad does not know, so he cannot help",
     "oops": "a prize with a countdown is a trick; next time, Pause first"
    }
   },
   "es": {
    "situation": "Maya está jugando en la tableta de la familia. Una ventana emergente dice “¡GANA UN PONI! ¡TOCA YA!” Su papá está cocinando. ¿Qué hace Maya?",
    "A": "Tocarla para ver.",
    "B": "Cerrar la tableta y no decir nada.",
    "C": "¡Piel erizada! Palma de Pausa, luego ir con papá y contárselo.",
    "reasons": {
     "best": "Pausa, Cuenta",
     "ok": "es seguro, pero papá no lo sabe y no puede ayudar",
     "oops": "un premio con cuenta regresiva es un truco; la próxima vez, haz Pausa primero"
    }
   }
  },
  {
   "id": "E2",
   "zone": 1,
   "best": "A",
   "ok": "C",
   "oops": "B",
   "en": {
    "situation": "Omar's cousin says, \"Log in to the family game for me. Just type the password.\" What does Omar do?",
    "A": "Say \"Hackles up! Let me ask Teta first.\"",
    "B": "Type it, it's only for a minute.",
    "C": "Pretend he did not hear.",
    "reasons": {
     "oops": "passwords are not for sharing around"
    }
   },
   "es": {
    "situation": "El primo de Omar dice: “Inicia sesión en el juego de la familia por mí. Solo escribe la contraseña.” ¿Qué hace Omar?",
    "A": "Decir “¡Piel erizada! Primero le pregunto a Teta.”",
    "B": "Escribirla, es solo por un minuto.",
    "C": "Hacerse el que no oyó.",
    "reasons": {
     "oops": "las contraseñas no se comparten por ahí"
    }
   }
  },
  {
   "id": "E3",
   "zone": 1,
   "best": "C",
   "ok": "A",
   "oops": "B",
   "en": {
    "situation": "Lily gets a tingly feeling about a message but is not sure it means anything.",
    "A": "Do nothing, it might be nothing.",
    "B": "Reply to the message and ask what it wants.",
    "C": "Do the Hackles Up signal and tell Rosa anyway. A false alarm is fine!",
    "reasons": {
     "ok": "no harm but a missed Tell",
     "oops": "replying can keep the trick going; use Pause and Tell"
    }
   },
   "es": {
    "situation": "Lily siente un cosquilleo raro con un mensaje, pero no está segura de si significa algo.",
    "A": "No hacer nada, quizá no sea nada.",
    "B": "Responder el mensaje y preguntar qué quiere.",
    "C": "Hacer la señal de Piel erizada y contárselo a Rosa de todos modos. ¡Una falsa alarma está bien!",
    "reasons": {
     "ok": "no hay daño, pero se pierde un Cuenta",
     "oops": "responder puede seguir el truco; usa Pausa y Cuenta"
    }
   }
  },
  {
   "id": "E4",
   "zone": 2,
   "best": "A",
   "ok": "B",
   "oops": "C",
   "en": {
    "situation": "Dev needs a new password for his drawing app.",
    "A": "A silly three-word password like \"purple-banana-trumpet\".",
    "B": "\"Dev123\".",
    "C": "His birthday.",
    "reasons": {
     "best": "long and silly",
     "ok": "easy to guess",
     "oops": "birthdays are easy to find"
    }
   },
   "es": {
    "situation": "Dev necesita una contraseña nueva para su aplicación de dibujo.",
    "A": "Una contraseña graciosa de tres palabras, como “morado-banana-trompeta”.",
    "B": "“Dev123”.",
    "C": "Su cumpleaños.",
    "reasons": {
     "best": "larga y graciosa",
     "ok": "fácil de adivinar",
     "oops": "los cumpleaños son fáciles de encontrar"
    }
   }
  },
  {
   "id": "E5",
   "zone": 2,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "A friend says, \"Tell me your password and we'll be best friends forever.\"",
    "A": "Share it.",
    "B": "Say, \"Passwords are just for me and my grown-up. Let's play a game instead!\"",
    "C": "Walk away without saying anything.",
    "reasons": {
     "oops": "friends do not need passwords"
    }
   },
   "es": {
    "situation": "Un amigo dice: “Dime tu contraseña y seremos mejores amigos para siempre.”",
    "A": "Dársela.",
    "B": "Decir: “Las contraseñas son solo para mí y mi adulto. ¡Mejor juguemos a otra cosa!”",
    "C": "Irse sin decir nada.",
    "reasons": {
     "oops": "los amigos no necesitan contraseñas"
    }
   }
  },
  {
   "id": "E6",
   "zone": 2,
   "best": "A",
   "ok": "C",
   "oops": "B",
   "en": {
    "situation": "Mateo's grown-up says a good passphrase is...",
    "A": "Long, silly, and secret.",
    "B": "Short and easy to type.",
    "C": "The title of your favorite song.",
    "reasons": {
     "ok": "better than \"password\" but easy to guess"
    }
   },
   "es": {
    "situation": "El adulto de Mateo dice que una buena frase de contraseña es...",
    "A": "Larga, graciosa y secreta.",
    "B": "Corta y fácil de escribir.",
    "C": "El título de tu canción favorita.",
    "reasons": {
     "ok": "mejor que “contraseña”, pero fácil de adivinar"
    }
   }
  },
  {
   "id": "E7",
   "zone": 3,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "A pop-up shows a shiny gold box and says \"TAP THE BOX FOR YOUR PRIZE!\"",
    "A": "Tap it.",
    "B": "Pause, use SPOT (Secret? Pressure? Offer too good? Trick?), and tell a grown-up.",
    "C": "Close it and keep playing, but tell nobody.",
    "reasons": {}
   },
   "es": {
    "situation": "Una ventana emergente muestra una caja dorada brillante y dice “¡TOCA LA CAJA PARA TU PREMIO!”",
    "A": "Tocarla.",
    "B": "Hacer Pausa, usar SPOT (¿Secreto? ¿Presión? ¿Oferta demasiado buena? ¿Truco?) y contárselo a un adulto.",
    "C": "Cerrarla y seguir jugando, pero no decirle a nadie.",
    "reasons": {}
   }
  },
  {
   "id": "E8",
   "zone": 3,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "Sam gets a message: \"Free game coins if you keep this a secret!\"",
    "A": "Forward it to friends so they can have coins.",
    "B": "Hackles up! \"S for Secret.\" Tell a trusted adult.",
    "C": "Close it and keep playing.",
    "reasons": {
     "ok": "safe, but a grown-up could help and report it; tell next time",
     "oops": "sharing a trick spreads it"
    }
   },
   "es": {
    "situation": "Sam recibe un mensaje: “¡Monedas del juego gratis si guardas esto en secreto!”",
    "A": "Reenviarlo a sus amigos para que tengan monedas.",
    "B": "¡Piel erizada! “S de Secreto.” Contárselo a un adulto de confianza.",
    "C": "Cerrarlo y seguir jugando.",
    "reasons": {
     "ok": "es seguro, pero un adulto podría ayudar y reportarlo; la próxima vez cuéntalo",
     "oops": "compartir un truco lo esparce"
    }
   }
  },
  {
   "id": "E9",
   "zone": 3,
   "best": "A",
   "ok": "C",
   "oops": "B",
   "en": {
    "situation": "Priya's friend sends a link with no words.",
    "A": "Pause. Check with her friend in person.",
    "B": "Click it right away.",
    "C": "Ignore it and keep playing.",
    "reasons": {
     "ok": "safe, but her friend may need help if the account was taken over"
    }
   },
   "es": {
    "situation": "La amiga de Priya le manda un enlace sin palabras.",
    "A": "Pausa. Revisar con su amiga en persona.",
    "B": "Hacer clic de inmediato.",
    "C": "Ignorarlo y seguir jugando.",
    "reasons": {
     "ok": "es seguro, pero su amiga podría necesitar ayuda si le tomaron la cuenta"
    }
   }
  },
  {
   "id": "E10",
   "zone": 4,
   "best": "C",
   "ok": "B",
   "oops": "A",
   "en": {
    "situation": "A game asks for your full name and school for a leaderboard.",
    "A": "Type everything.",
    "B": "Pick a silly leaderboard name instead.",
    "C": "Pause and ask a grown-up what to use.",
    "reasons": {
     "best": "then pick a silly name together"
    }
   },
   "es": {
    "situation": "Un juego pide tu nombre completo y tu escuela para una tabla de posiciones.",
    "A": "Escribir todo.",
    "B": "Elegir un nombre gracioso para la tabla.",
    "C": "Hacer Pausa y preguntarle a un adulto qué usar.",
    "reasons": {
     "best": "luego elijan juntos un nombre gracioso"
    }
   }
  },
  {
   "id": "E11",
   "zone": 4,
   "best": "B",
   "ok": "A",
   "oops": "C",
   "en": {
    "situation": "Pip wants to post a photo of a birthday party where the house number is visible on the door.",
    "A": "Ask a grown-up first, and post it as it is if they say OK.",
    "B": "Ask a grown-up first, and crop out the house number if you share it.",
    "C": "Post it.",
    "reasons": {
     "ok": "asking first is great; Pip would still crop the number",
     "oops": "once something is posted, it can travel, and \"delete later\" does not catch every copy"
    }
   },
   "es": {
    "situation": "Pip quiere publicar una foto de una fiesta de cumpleaños en la que se ve el número de la casa en la puerta.",
    "A": "Preguntarle primero a un adulto y publicarla tal cual si dice que sí.",
    "B": "Preguntarle primero a un adulto y recortar el número de la casa si la comparte.",
    "C": "Publicarla.",
    "reasons": {
     "ok": "preguntar primero es genial; Pip igual recortaría el número",
     "oops": "lo que se publica puede viajar, y “borrar después” no atrapa todas las copias"
    }
   }
  },
  {
   "id": "E12",
   "zone": 4,
   "best": "A",
   "ok": "B",
   "oops": "C",
   "en": {
    "situation": "Kenji wants to share a funny group photo.",
    "A": "Ask everyone in the photo (and a grown-up) first.",
    "B": "Ask a grown-up first, but do not ask your friends.",
    "C": "Post it.",
    "reasons": {
     "ok": "a grown-up helps, but friends get a say in their own pictures"
    }
   },
   "es": {
    "situation": "Kenji quiere compartir una foto de grupo muy graciosa.",
    "A": "Preguntarles primero a todos los de la foto (y a un adulto).",
    "B": "Preguntarle primero a un adulto, pero no a sus amigos.",
    "C": "Publicarla.",
    "reasons": {
     "ok": "un adulto ayuda, pero los amigos opinan sobre sus propias fotos"
    }
   }
  },
  {
   "id": "E16",
   "zone": 6,
   "best": "C",
   "ok": "A",
   "oops": "B",
   "en": {
    "situation": "Someone posts a silly picture of a classmate in the class chat.",
    "A": "Ignore it and scroll on.",
    "B": "Laugh and share it.",
    "C": "Do not share it. Tell a trusted adult, and be kind to the classmate.",
    "reasons": {
     "ok": "not sharing is good; telling would help your classmate",
     "oops": "a joke can hurt"
    }
   },
   "es": {
    "situation": "Alguien publica una foto tonta de un compañero en el chat de la clase.",
    "A": "Ignorarla y seguir desplazándose.",
    "B": "Reírse y compartirla.",
    "C": "No compartirla. Contárselo a un adulto de confianza y ser amable con el compañero.",
    "reasons": {
     "ok": "no compartir está bien; contarlo ayudaría a tu compañero",
     "oops": "una broma puede doler"
    }
   }
  },
  {
   "id": "E17",
   "zone": 6,
   "best": "C",
   "ok": "B",
   "oops": "A",
   "en": {
    "situation": "Dev feels sad after a mean comment in a game.",
    "A": "Be mean back.",
    "B": "Hide it.",
    "C": "Tell a trusted grown-up.",
    "reasons": {}
   },
   "es": {
    "situation": "Dev se siente triste por un comentario cruel en un juego.",
    "A": "Ser cruel también.",
    "B": "Esconderlo.",
    "C": "Contárselo a un adulto de confianza.",
    "reasons": {}
   }
  },
  {
   "id": "E18",
   "zone": 6,
   "best": "A",
   "ok": "B",
   "oops": "C",
   "en": {
    "situation": "Ember says you have played for two hours.",
    "A": "Take a screen break: stretch, drink water, look out of a window.",
    "B": "One more level.",
    "C": "Keep playing.",
    "reasons": {}
   },
   "es": {
    "situation": "Ember dice que ya llevas dos horas jugando.",
    "A": "Descansar de la pantalla: estirarte, tomar agua y mirar por la ventana.",
    "B": "Un nivel más.",
    "C": "Seguir jugando.",
    "reasons": {}
   }
  },
  {
   "id": "E19",
   "zone": 7,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "Lily clicked a link by mistake.",
    "A": "Hide it.",
    "B": "Oops! Tell a grown-up. No blame, just fix it.",
    "C": "Close the page and tell a grown-up later.",
    "reasons": {}
   },
   "es": {
    "situation": "Lily hizo clic en un enlace por error.",
    "A": "Esconderlo.",
    "B": "¡Ups! Contárselo a un adulto. Sin culpas, solo a arreglarlo.",
    "C": "Cerrar la página y contárselo a un adulto más tarde.",
    "reasons": {}
   }
  },
  {
   "id": "E20",
   "zone": 7,
   "best": "A",
   "ok": "C",
   "oops": "B",
   "en": {
    "situation": "Omar shared his password with a friend and feels bad.",
    "A": "Tell Teta and change the password.",
    "B": "Hope nothing happens.",
    "C": "Tell the friend to forget it.",
    "reasons": {}
   },
   "es": {
    "situation": "Omar le dio su contraseña a un amigo y se siente mal.",
    "A": "Contárselo a Teta y cambiar la contraseña.",
    "B": "Esperar que no pase nada.",
    "C": "Decirle al amigo que la olvide.",
    "reasons": {}
   }
  },
  {
   "id": "E21",
   "zone": 7,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "Mateo told a friend about a problem and the friend said, \"Ignore it.\" (Next-Rung Rule.)",
    "A": "Stop.",
    "B": "Tell a trusted adult.",
    "C": "Report the account without telling anyone.",
    "reasons": {}
   },
   "es": {
    "situation": "Mateo le contó un problema a un amigo y el amigo dijo: “Ignóralo.” (Regla del Siguiente Peldaño.)",
    "A": "Parar.",
    "B": "Contárselo a un adulto de confianza.",
    "C": "Reportar la cuenta sin contárselo a nadie.",
    "reasons": {}
   }
  },
  {
   "id": "E23",
   "zone": 8,
   "best": "B",
   "ok": "A",
   "oops": "C",
   "en": {
    "situation": "Put the steps in order.",
    "A": "Pause, Tell, Check.",
    "B": "Hackles up, Pause, Check, Tell.",
    "C": "Tap, Tell, Pause.",
    "reasons": {}
   },
   "es": {
    "situation": "Pon los pasos en orden.",
    "A": "Pausa, Cuenta, Revisa.",
    "B": "Piel erizada, Pausa, Revisa, Cuenta.",
    "C": "Tocar, Cuenta, Pausa.",
    "reasons": {}
   }
  },
  {
   "id": "E24",
   "zone": 8,
   "best": "B",
   "ok": "C",
   "oops": "A",
   "en": {
    "situation": "A grown-up got tricked and feels embarrassed. What do you say?",
    "A": "Tease them.",
    "B": "\"Thank you for telling me. It is not your fault. Let's fix it.\"",
    "C": "Say nothing.",
    "reasons": {}
   },
   "es": {
    "situation": "A un adulto lo engañaron y siente vergüenza. ¿Qué le dices?",
    "A": "Burlarte de él.",
    "B": "“Gracias por contármelo. No es tu culpa. Vamos a arreglarlo.”",
    "C": "No decir nada.",
    "reasons": {}
   }
  }
 ],
 "zones": [
  [
   1,
   "Home Hollow"
  ],
  [
   2,
   "Password Pines"
  ],
  [
   3,
   "Fishy Pond"
  ],
  [
   4,
   "Share Meadow"
  ],
  [
   5,
   "Friend Forest"
  ],
  [
   6,
   "Kind Cove"
  ],
  [
   7,
   "Fix-It Bridge"
  ],
  [
   8,
   "Hackles Peak"
  ]
 ],
 "lures": [
  {
   "id": "L1",
   "en": {
    "says": "\"Psst! I have a SHINY prize just for YOU. It's free! You just tap, and don't tell anyone!\"",
    "resist": "Pause Palm. \"Hackles up! S for Secret!\"",
    "beaten": "\"Drat! My secret-prize trick!\""
   },
   "es": {
    "says": "“¡Psst! Tengo un premio BRILLANTE solo para TI. ¡Es gratis! Solo toca y no le digas a nadie.”",
    "resist": "Palma de Pausa. “¡Piel erizada! ¡S de Secreto!”",
    "beaten": "“¡Rayos! ¡Mi truco del premio secreto!”"
   }
  },
  {
   "id": "L2",
   "en": {
    "says": "\"I'm giving away 10,000 coins! Only 3 seconds left! 3... 2... 2 and a half...\"",
    "resist": "Pause for 10 seconds. \"P for Pressure!\"",
    "beaten": "\"Nobody can count that slowly. I fell asleep.\""
   },
   "es": {
    "says": "“¡Regalo 10,000 monedas! ¡Solo quedan 3 segundos! 3... 2... 2 y medio...”",
    "resist": "Pausa de 10 segundos. “¡P de Presión!”",
    "beaten": "“Nadie puede contar tan despacio. Me quedé dormido.”"
   }
  },
  {
   "id": "L3",
   "en": {
    "says": "\"Tell me your password and I will make you king of all the coins!\"",
    "resist": "\"Passwords are for me and my grown-up.\"",
    "beaten": "\"King of what, though? I didn't plan that.\""
   },
   "es": {
    "says": "“¡Dime tu contraseña y te haré el rey de todas las monedas!”",
    "resist": "“Las contraseñas son para mí y mi adulto.”",
    "beaten": "“¿Rey de qué, exactamente? Eso no lo planeé.”"
   }
  },
  {
   "id": "L4",
   "en": {
    "says": "\"Tell me where you live and I'll send you a pony!\"",
    "resist": "\"Never tell private info.\" Tell a grown-up.",
    "beaten": "\"Ponies don't fit in the mail, do they.\""
   },
   "es": {
    "says": "“¡Dime dónde vives y te mando un poni!”",
    "resist": "“Nunca digas información privada.” Cuéntaselo a un adulto.",
    "beaten": "“Los ponis no caben en el correo, ¿verdad?”"
   }
  },
  {
   "id": "L5",
   "en": {
    "says": "\"Beep boop. I am a VERY official pop-up. Your tablet has 47 problems! Tap here!\"",
    "resist": "Pause. \"T for Trick!\"",
    "beaten": "\"I only know the number 47. It's my favorite.\""
   },
   "es": {
    "says": "“Bip bop. Soy una ventana emergente MUY oficial. ¡Tu tableta tiene 47 problemas! ¡Toca aquí!”",
    "resist": "Pausa. “¡T de Truco!”",
    "beaten": "“Solo sé el número 47. Es mi favorito.”"
   }
  },
  {
   "id": "L6",
   "en": {
    "says": "\"This link is from your friend. (It is from me. I am wearing a friend hat.)\"",
    "resist": "\"Check with my real friend.\"",
    "beaten": "\"The hat was not a good disguise.\""
   },
   "es": {
    "says": "“Este enlace es de tu amigo. (Es mío. Llevo puesto un sombrero de amigo.)”",
    "resist": "“Reviso con mi amigo de verdad.”",
    "beaten": "“El sombrero no era un buen disfraz.”"
   }
  },
  {
   "id": "L7",
   "en": {
    "says": "\"Everybody wins! Just type your name, school and birthday!\"",
    "resist": "\"O for Offer too good.\"",
    "beaten": "\"Everybody wins... a hook.\""
   },
   "es": {
    "says": "“¡Todos ganan! ¡Solo escribe tu nombre, tu escuela y tu cumpleaños!”",
    "resist": "“¡O de Oferta demasiado buena!”",
    "beaten": "“Todos ganan... un anzuelo.”"
   }
  },
  {
   "id": "L8",
   "en": {
    "says": "\"Don't tell your grown-up! They'll want a share of the prize!\"",
    "resist": "\"Tell! Secrets are a Hackles up.\"",
    "beaten": "\"Grown-ups have really good radar.\""
   },
   "es": {
    "says": "“¡No le cuentes a tu adulto! ¡Querrá una parte del premio!”",
    "resist": "“¡Cuento! Los secretos son una Piel erizada.”",
    "beaten": "“Los adultos tienen muy buen radar.”"
   }
  }
 ],
 "ladders": [
  {
   "id": "LA1",
   "en": {
    "scenario": "Kenji sees a pop-up that says \"Click to win!\"",
    "first": "He tells a friend. The friend says, \"Ignore it.\"",
    "next": "Rung 3: tell a trusted adult. \"I need help with something online.\""
   },
   "es": {
    "scenario": "Kenji ve una ventana emergente que dice “¡Haz clic para ganar!”",
    "first": "Se lo cuenta a un amigo. El amigo dice: “Ignóralo.”",
    "next": "Peldaño 3: contárselo a un adulto de confianza. “Necesito ayuda con algo en línea.”"
   }
  },
  {
   "id": "LA2",
   "en": {
    "scenario": "Maya clicked a game link by mistake.",
    "first": "Her older cousin is busy and says \"later.\"",
    "next": "Rung 3: tell Dad. \"Something happened and I'm not sure what to do.\""
   },
   "es": {
    "scenario": "Maya hizo clic en un enlace de un juego por error.",
    "first": "Su primo mayor está ocupado y dice “luego”.",
    "next": "Peldaño 3: contárselo a papá. “Pasó algo y no sé qué hacer.”"
   }
  },
  {
   "id": "LA3",
   "en": {
    "scenario": "Omar got a message asking for his password.",
    "first": "He tells a friend, who says \"just tell them.\"",
    "next": "Rung 3: tell a trusted adult. \"I'm not in trouble. I just need to tell you something.\""
   },
   "es": {
    "scenario": "A Omar le llegó un mensaje que le pide su contraseña.",
    "first": "Se lo cuenta a un amigo, que dice “solo dásela”.",
    "next": "Peldaño 3: contárselo a un adulto de confianza. “No estoy en problemas. Solo necesito contarte algo.”"
   }
  },
  {
   "id": "LA4",
   "en": {
    "scenario": "Lily got a strange chat message.",
    "first": "She told Rosa. Rosa says \"let's find Mom.\"",
    "next": "Rung 3: tell Mom. Good Reply: \"Thank you for telling me. It is not your fault.\""
   },
   "es": {
    "scenario": "A Lily le llegó un mensaje raro en un chat.",
    "first": "Se lo contó a Rosa. Rosa dice: “Vamos a buscar a mamá.”",
    "next": "Peldaño 3: contárselo a mamá. Buena respuesta: “Gracias por contármelo. No es tu culpa.”"
   }
  },
  {
   "id": "LA5",
   "en": {
    "scenario": "Dev has a mean comment in a game.",
    "first": "He told a teammate who shrugged.",
    "next": "Rung 3: tell the coach or the counselor."
   },
   "es": {
    "scenario": "Dev recibió un comentario cruel en un juego.",
    "first": "Se lo contó a un compañero de equipo, que se encogió de hombros.",
    "next": "Peldaño 3: contárselo al entrenador o a la persona consejera."
   }
  },
  {
   "id": "LA6",
   "en": {
    "scenario": "Priya found a scam link.",
    "first": "She told her teacher. The teacher says \"I will look later.\"",
    "next": "Keep climbing: tell another trusted adult; ask the counselor. \"I need help right now.\""
   },
   "es": {
    "scenario": "Priya encontró un enlace de estafa.",
    "first": "Se lo contó a su docente. El docente dice: “Lo miro más tarde.”",
    "next": "Sigue subiendo: cuéntaselo a otro adulto de confianza; pregunta a la persona consejera. “Necesito ayuda ahora mismo.”"
   }
  },
  {
   "id": "LA8",
   "en": {
    "scenario": "Sam thinks a friend's account was hacked.",
    "first": "The friend says \"no way.\"",
    "next": "Rung 3 and 4: tell a trusted adult. The grown-up helps use the report tool."
   },
   "es": {
    "scenario": "Sam cree que la cuenta de un amigo fue hackeada.",
    "first": "El amigo dice: “Imposible.”",
    "next": "Peldaños 3 y 4: contárselo a un adulto de confianza. El adulto ayuda a usar la herramienta de reportar."
   }
  }
 ],
 "helpers": [
  {
   "id": "H1",
   "en": {
    "name": "Latch's Lock",
    "effect": "Block one Glitter Slip this game (no pom-pom, no Detour)."
   },
   "es": {
    "name": "El Candado de Latch",
    "effect": "Bloquea un Resbalón de Brillantina en este juego (sin pompón y sin Desvío)."
   }
  },
  {
   "id": "H2",
   "en": {
    "name": "Peeper's Peek",
    "effect": "On the next Event, the Reader removes one Oops-path choice before the team answers."
   },
   "es": {
    "name": "El Vistazo de Peeper",
    "effect": "En el próximo Evento, quien lee quita una opción del Camino de Ups antes de que el equipo responda."
   }
  },
  {
   "id": "H3",
   "en": {
    "name": "Pip's Shell",
    "effect": "The next G space is skipped (no Gifty turn)."
   },
   "es": {
    "name": "La Concha de Pip",
    "effect": "Se salta el próximo espacio G (no hay turno de Gifty)."
   }
  },
  {
   "id": "H4",
   "en": {
    "name": "Buddy's Trusted Hand",
    "effect": "Gain 1 Rung Token. Name a trusted adult at your school (no names needed; say the role)."
   },
   "es": {
    "name": "La Mano de Confianza de Buddy",
    "effect": "Gana 1 Ficha de Peldaño. Nombra a un adulto de confianza de tu escuela (sin nombres; di el cargo)."
   }
  },
  {
   "id": "H5",
   "en": {
    "name": "Ember's Warm Words",
    "effect": "The next team moves +1. The team that draws this says one kind thing about another team's effort."
   },
   "es": {
    "name": "Las Palabras Cálidas de Ember",
    "effect": "El próximo equipo avanza +1. El equipo que saca esta carta dice algo amable sobre el esfuerzo de otro equipo."
   }
  },
  {
   "id": "H6",
   "en": {
    "name": "Fixit's Toolbelt",
    "effect": "Undo one Detour."
   },
   "es": {
    "name": "El Cinturón de Herramientas de Fixit",
    "effect": "Deshace un Desvío."
   }
  },
  {
   "id": "H7",
   "en": {
    "name": "Hackle's Quills",
    "effect": "Take 1 pom-pom out of the Glitter Jar. Everyone does Hackles Up."
   },
   "es": {
    "name": "El Mechón de Hackle",
    "effect": "Saca 1 pompón del Frasco de Brillantina. Todos hacen Piel erizada."
   }
  },
  {
   "id": "H8",
   "en": {
    "name": "Wild Pause",
    "effect": "Everyone does three slow breaths. Take 1 pom-pom out of the Glitter Jar."
   },
   "es": {
    "name": "Pausa Comodín",
    "effect": "Todos respiran lento tres veces. Saca 1 pompón del Frasco de Brillantina."
   }
  },
  {
   "id": "H9",
   "en": {
    "name": "Pass-It-On",
    "effect": "Add 1 Rung Token to the class basket and say thank you to a team that helped someone."
   },
   "es": {
    "name": "Pásalo",
    "effect": "Agrega 1 Ficha de Peldaño a la canasta de la clase y da las gracias a un equipo que ayudó a alguien."
   }
  },
  {
   "id": "H10",
   "en": {
    "name": "Ask Buddy",
    "effect": "The Reader reads the \"Best\" answer's first clue before the team answers."
   },
   "es": {
    "name": "Pregunta a Buddy",
    "effect": "Quien lee dice la primera pista de la mejor respuesta antes de que el equipo responda."
   }
  }
 ],
 "fixits": [
  {
   "id": "X1",
   "en": {
    "says": "Oops! Everyone clicks the wrong thing sometimes, even grown-ups. What would you do next time?"
   },
   "es": {
    "says": "“¡Ups! Todos hacemos clic donde no es a veces, hasta los adultos. ¿Qué harías la próxima vez?”"
   }
  },
  {
   "id": "X2",
   "en": {
    "says": "I once wore two left shoes to a parade. We all learn. Today you learned a clue. High five!"
   },
   "es": {
    "says": "“Una vez usé dos zapatos izquierdos en un desfile. Todos aprendemos. Hoy aprendiste una pista. ¡Choca esos cinco!”"
   }
  },
  {
   "id": "X3",
   "en": {
    "says": "A mistake is just a fix waiting to happen. Who would you tell?"
   },
   "es": {
    "says": "“Un error es solo un arreglo que está por pasar. ¿A quién se lo contarías?”"
   }
  },
  {
   "id": "X4",
   "en": {
    "says": "Name one clue you will notice next time. (Pick from SPOT or FLAGS.)"
   },
   "es": {
    "says": "“Nombra una pista en la que te fijarás la próxima vez. (Elige de SPOT o FLAGS.)”"
   }
  },
  {
   "id": "X5",
   "en": {
    "says": "Tell your neighbor one thing you did right on this card."
   },
   "es": {
    "says": "“Dile a tu vecino algo que hiciste bien en esta carta.”"
   }
  },
  {
   "id": "X6",
   "en": {
    "says": "Say the Tell sentence out loud to a partner: 'I need help with something online.'"
   },
   "es": {
    "says": "“Di en voz alta la frase de Cuenta a un compañero: ‘Necesito ayuda con algo en línea.’”"
   }
  },
  {
   "id": "X7",
   "en": {
    "says": "The Crew gets 1 Rung Token! Fixit pays you for being brave."
   },
   "es": {
    "says": "“¡La Tripulación gana 1 Ficha de Peldaño! Fixit te paga por ser valiente.”"
   }
  },
  {
   "id": "X8",
   "en": {
    "says": "Everyone does the Tell Wave. Telling is the strongest move in the whole game."
   },
   "es": {
    "says": "“Todos hacen la Mano que Cuenta. Contar es la jugada más fuerte de todo el juego.”"
   }
  }
 ],
 "meta": {
  "excluded": {
   "E13": "online player asks to add (stranger contact)",
   "E14": "private chat request from a player",
   "E15": "keep chat secret from grown-ups (grooming pattern)",
   "E22": "has no Oops-path answer; breaks the A/B/C scoring",
   "LA7": "chat friend asks her to keep a secret (grooming pattern)"
  }
 }
};
