/* Help Ladder Trail: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "trail.title": "Help Ladder Trail",
    "trail.kicker": "Plate 6 of 6",
    "trail.lead": "The whole class hikes from Home Hollow to Hackles Peak. Teams take turns choosing what to do. Gifty the Too-Good Box tries to tempt the Crew, and the Help Ladder helps them climb. The class cannot lose.",
    "trail.promises": "A false alarm is fine. It is never your fault. Nobody moves backward for an answer.",
    "trail.mode": "How long?",
    "trail.mode.mini": "10 minutes: Mini Trail (15 spaces)",
    "trail.mode.full": "30 minutes: Full Trail (40 spaces)",
    "trail.teams": "How many teams?",
    "trail.teamsNote": "Teams use crew names. Nobody types anything.",
    "trail.start": "Start the hike",
    "trail.story": "The Hackles Crew is going on a hike to the top of Hackles Peak. A shiny gold box named Gifty is on the path. Everything Gifty offers has a hook. He is silly, not scary, and a calm Pause beats him every time.",
    "trail.zone": "Zone {n}: {name}",
    "trail.zone.1": "Home Hollow", "trail.zone.2": "Password Pines", "trail.zone.3": "Fishy Pond", "trail.zone.4": "Share Meadow",
    "trail.zone.5": "Friend Forest", "trail.zone.6": "Kind Cove", "trail.zone.7": "Fix-It Bridge", "trail.zone.8": "Hackles Peak",
    "trail.map": "The trail",
    "trail.mapAt": "The Crew Token is on space {n} of {total}.",
    "trail.mapStart": "The Crew Token is at the start.",
    "trail.legend": "E trail, L ladder, H helper, B breathe, G Gifty's gift stop, finish at the Peak",
    "trail.sp.E": "trail space", "trail.sp.L": "ladder space", "trail.sp.H": "helper space", "trail.sp.B": "breathe space", "trail.sp.G": "Gifty's gift stop", "trail.sp.F": "Hackles Peak",
    "trail.status": "Crew status",
    "trail.jar": "Glitter Jar: {n} of 2",
    "trail.rungs": "Rung Tokens: {n}",
    "trail.ladderFill": "Class Ladder: {n} of 3 rungs",
    "trail.ribbons": "Rescue Ribbons: {n}",
    "trail.turn": "Turn {n}",
    "trail.active": "Team {name}",
    "trail.activeSub": "Every team whispers an answer. This team's choice moves the Crew.",
    "trail.choose": "What does the Crew do?",
    "trail.optA": "A (circle)", "trail.optB": "B (triangle)", "trail.optC": "C (square)",
    "trail.pass": "Pass to the Guides",
    "trail.passNote": "The other teams decide. It counts as an OK move.",
    "trail.hintBuddy": "Ask Buddy says: the best answer begins \"{t}\".",
    "trail.result": "What happened",
    "trail.best": "Best choice",
    "trail.ok": "OK choice",
    "trail.oops": "Fixit's Oops Path",
    "trail.youChose": "your team's choice",
    "trail.reason.best": "This is the strongest move.",
    "trail.reason.ok": "This is safe, and there is a stronger move.",
    "trail.reason.oops": "This leads to Fixit's help. Everyone is fine, and now you know a clue for next time.",
    "trail.moved": "The Crew moves {n} spaces.",
    "trail.movedBonus": "The Crew moves {n} spaces ({b} extra from Ember's Warm Words).",
    "trail.tokenEarned": "A Tell is a strong move. The Crew earns a Rung Token.",
    "trail.moveBtn": "Move the Crew Token",
    "trail.continue": "Continue",
    "trail.fixit": "Fixit says",
    "trail.land.E": "A calm place to stand. Everyone does the Hackles Up signal.",
    "trail.land.S": "At the start.",
    "trail.land.L": "Ladder space! The class climbs the Help Ladder.",
    "trail.land.H": "Helper space! The Crew draws a Helper card.",
    "trail.land.B": "Breathe space! Take three slow breaths together, then do Hackles Up, Pause, Check, Tell.",
    "trail.land.G": "Gifty's gift stop! Gifty has something to say.",
    "trail.ladder.scene": "What happened",
    "trail.ladder.first": "When they told someone first",
    "trail.ladder.q": "What does the class do next?",
    "trail.ladder.good": "Yes. Keep climbing until someone helps. The Crew fills a rung and earns a Rung Token.",
    "trail.ladder.try": "Good try. The Next-Rung Rule says keep climbing, so this is the move that does that. The Crew still fills a rung and earns a Rung Token.",
    "trail.ladder.say": "Say a sentence together: \"I need help with something online.\" or \"Something happened and I'm not sure what to do.\" or \"I'm not in trouble. I just need to tell you something.\"",
    "trail.ladder.reply": "A good grown-up reply: \"Thank you for telling me. It is not your fault. Let's figure it out together.\"",
    "trail.ladder.stop": "Stop here and hope it goes away.",
    "trail.ladder.hide": "Keep it to myself and tell nobody else.",
    "trail.wish": "Ladder Wish! The Class Ladder is full. Choose one:",
    "trail.wish.jar": "Empty the Glitter Jar",
    "trail.wish.skip": "Skip ahead 3 spaces",
    "trail.wish.helpers": "Draw 2 Helper cards",
    "trail.wish.done": "Wish granted.",
    "trail.helper": "Helper card: {name}",
    "trail.breathe.done": "We breathed",
    "trail.breathe.jar": "One pom-pom comes out of the Glitter Jar.",
    "trail.gifty": "Gifty's turn",
    "trail.gifty.says": "Gifty says",
    "trail.gifty.resist": "The class resists: everyone shows the Pause Palm and names the flag.",
    "trail.gifty.how": "How to resist",
    "trail.gifty.resisted": "We resisted! Flip Gifty's coin",
    "trail.coin.star": "Star side: Gifty is beaten! Cheer.",
    "trail.coin.beaten": "Gifty says: {t}",
    "trail.coin.hook": "Hook side: a Glitter Slip. Even when everyone does everything right, a clever trick can sometimes get through. That is true in real life and it is never anyone's fault.",
    "trail.slip.free": "The first Glitter Slip is free. No Detour.",
    "trail.slip.blocked": "Latch's Lock blocks the slip. No pom-pom and no Detour.",
    "trail.slip.undone": "Fixit's Toolbelt undoes the Detour.",
    "trail.slip.detour": "The Crew slips back {n} spaces (a Detour). A pom-pom goes in the Glitter Jar.",
    "trail.slip.jar": "A pom-pom goes in the Glitter Jar.",
    "trail.cancel": "Spend a Rung Token and say a Tell sentence to cancel the Detour",
    "trail.cancelled": "The class told someone, and the glitter was swept away. The Crew is back where it was.",
    "trail.storm": "Sparkle Storm!",
    "trail.storm.b": "The jar overflows in a silly glitter blizzard. Everyone stands and does jazz hands. Then each team says one Help Ladder sentence: tell a friend, tell a trusted adult, or report. The token does not move back. The class earns a Rescue Ribbon.",
    "trail.storm.done": "We said our sentences",
    "trail.sunrise": "Teacher: Sunrise Wind",
    "trail.sunrise.help": "Lifts the Crew toward the Peak if time is short.",
    "trail.sunrise.done": "A friendly wind lifts the Crew up the Peak Path!",
    "trail.sunrise.no": "The Crew is already close to the Peak.",
    "trail.end.h": "Hackles Peak!",
    "trail.end.sub": "The class reached the top together.",
    "trail.tier.gold": "Gold Peak",
    "trail.tier.silver": "Silver Peak",
    "trail.tier.bronze": "Bronze Peak",
    "trail.tier.b.gold": "No Sparkle Storms.",
    "trail.tier.b.silver": "One Sparkle Storm.",
    "trail.tier.b.bronze": "Two or more Sparkle Storms.",
    "trail.tier.note": "Every tier earns the same cheer. A Rescue Ribbon means you climbed the Ladder. That is exactly the point. The tier mostly shows how the coin fell, so nobody is praised or scolded for it.",
    "trail.bigpause": "The Big Pause",
    "trail.bigpause.b": "Everyone does Hackles Up, then the Pause Palm with a slow breath, then Check Eyes, then the Tell Wave. Each team says one thing it will remember.",
    "trail.gifty.final": "Gifty says: \"Fine, fine, you win. But I'd like it noted that my gift was very shiny.\"",
    "trail.again": "Hike again",
    "trail.lab": "Back to Lab home",
    "trail.live.event": "Turn {n}. Team {team}. {t}",
    "trail.live.result": "{c}. The Crew moves {n} spaces to space {p}.",
    "trail.live.slip": "Glitter Slip. Jar {j} of 2.",
    "trail.live.beaten": "Gifty is beaten."
  },
  es: {
    "trail.title": "Sendero de la Escalera de Ayuda",
    "trail.kicker": "Lámina 6 de 6",
    "trail.lead": "Toda la clase camina desde el Valle de Casa hasta la Cima Hackles. Los equipos se turnan para elegir qué hacer. Gifty, la Caja Demasiado Buena, intenta tentar a la Tripulación y la Escalera de Ayuda la ayuda a subir. La clase no puede perder.",
    "trail.promises": "Una falsa alarma está bien. Nunca es tu culpa. Nadie retrocede por una respuesta.",
    "trail.mode": "¿Cuánto tiempo?",
    "trail.mode.mini": "10 minutos: Mini Sendero (15 espacios)",
    "trail.mode.full": "30 minutos: Sendero Completo (40 espacios)",
    "trail.teams": "¿Cuántos equipos?",
    "trail.teamsNote": "Los equipos usan nombres de la tripulación. Nadie escribe nada.",
    "trail.start": "Empezar la caminata",
    "trail.story": "La Tripulación Hackles sube la montaña hasta la Cima Hackles. Una caja dorada y brillante llamada Gifty está en el camino. Todo lo que ofrece Gifty tiene un anzuelo. Es gracioso, no da miedo, y una Pausa tranquila lo vence siempre.",
    "trail.zone": "Zona {n}: {name}",
    "trail.zone.1": "Valle de Casa", "trail.zone.2": "Pinos de Contraseña", "trail.zone.3": "Estanque Sospechoso", "trail.zone.4": "Pradera de Compartir",
    "trail.zone.5": "Bosque de Amigos", "trail.zone.6": "Cala Amable", "trail.zone.7": "Puente Arreglatodo", "trail.zone.8": "Cima Hackles",
    "trail.map": "El sendero",
    "trail.mapAt": "La Ficha de la Tripulación está en el espacio {n} de {total}.",
    "trail.mapStart": "La Ficha de la Tripulación está en la salida.",
    "trail.legend": "E sendero, L escalera, H ayudante, B respirar, G parada de regalos de Gifty, la meta en la Cima",
    "trail.sp.E": "espacio de sendero", "trail.sp.L": "espacio de escalera", "trail.sp.H": "espacio de ayudante", "trail.sp.B": "espacio de respirar", "trail.sp.G": "parada de regalos de Gifty", "trail.sp.F": "Cima Hackles",
    "trail.status": "Estado de la Tripulación",
    "trail.jar": "Frasco de Brillantina: {n} de 2",
    "trail.rungs": "Fichas de Peldaño: {n}",
    "trail.ladderFill": "Escalera de la Clase: {n} de 3 peldaños",
    "trail.ribbons": "Listones de Rescate: {n}",
    "trail.turn": "Turno {n}",
    "trail.active": "Equipo {name}",
    "trail.activeSub": "Todos los equipos susurran una respuesta. La elección de este equipo mueve a la Tripulación.",
    "trail.choose": "¿Qué hace la Tripulación?",
    "trail.optA": "A (círculo)", "trail.optB": "B (triángulo)", "trail.optC": "C (cuadrado)",
    "trail.pass": "Pasar a los Guías",
    "trail.passNote": "Deciden los otros equipos. Cuenta como una jugada OK.",
    "trail.hintBuddy": "Pregunta a Buddy dice: la mejor respuesta empieza con “{t}”.",
    "trail.result": "Lo que pasó",
    "trail.best": "Mejor opción",
    "trail.ok": "Opción OK",
    "trail.oops": "El Camino de ¡Ups! de Fixit",
    "trail.youChose": "la elección de tu equipo",
    "trail.reason.best": "Esta es la jugada más fuerte.",
    "trail.reason.ok": "Esta es segura, y hay una jugada más fuerte.",
    "trail.reason.oops": "Esto lleva a la ayuda de Fixit. Todos están bien, y ahora sabes una pista para la próxima vez.",
    "trail.moved": "La Tripulación avanza {n} espacios.",
    "trail.movedBonus": "La Tripulación avanza {n} espacios ({b} extra por las Palabras Cálidas de Ember).",
    "trail.tokenEarned": "Contar es una jugada fuerte. La Tripulación gana una Ficha de Peldaño.",
    "trail.moveBtn": "Mover la Ficha de la Tripulación",
    "trail.continue": "Continuar",
    "trail.fixit": "Fixit dice",
    "trail.land.E": "Un lugar tranquilo para pararse. Todos hacen la señal de Piel erizada.",
    "trail.land.S": "En la salida.",
    "trail.land.L": "¡Espacio de escalera! La clase sube la Escalera de Ayuda.",
    "trail.land.H": "¡Espacio de ayudante! La Tripulación saca una carta de Ayudante.",
    "trail.land.B": "¡Espacio de respirar! Respiren lento tres veces juntos y luego hagan Piel erizada, Pausa, Revisa, Cuenta.",
    "trail.land.G": "¡Parada de regalos de Gifty! Gifty tiene algo que decir.",
    "trail.ladder.scene": "Lo que pasó",
    "trail.ladder.first": "Cuando se lo contó a alguien primero",
    "trail.ladder.q": "¿Qué hace la clase ahora?",
    "trail.ladder.good": "Sí. Sigue subiendo hasta que alguien ayude. La Tripulación llena un peldaño y gana una Ficha de Peldaño.",
    "trail.ladder.try": "Buen intento. La Regla del Siguiente Peldaño dice que sigas subiendo, así que esta es la jugada que lo hace. La Tripulación igual llena un peldaño y gana una Ficha de Peldaño.",
    "trail.ladder.say": "Digan una frase juntos: “Necesito ayuda con algo en línea.” o “Pasó algo y no sé qué hacer.” o “No estoy en problemas. Solo necesito contarte algo.”",
    "trail.ladder.reply": "Una buena respuesta de un adulto: “Gracias por contármelo. No es tu culpa. Vamos a resolverlo juntos.”",
    "trail.ladder.stop": "Parar aquí y esperar que se pase solo.",
    "trail.ladder.hide": "Guardármelo y no decírselo a nadie más.",
    "trail.wish": "¡Deseo de la Escalera! La Escalera de la Clase está llena. Elige uno:",
    "trail.wish.jar": "Vaciar el Frasco de Brillantina",
    "trail.wish.skip": "Avanzar 3 espacios",
    "trail.wish.helpers": "Sacar 2 cartas de Ayudante",
    "trail.wish.done": "Deseo concedido.",
    "trail.helper": "Carta de Ayudante: {name}",
    "trail.breathe.done": "Ya respiramos",
    "trail.breathe.jar": "Sale un pompón del Frasco de Brillantina.",
    "trail.gifty": "El turno de Gifty",
    "trail.gifty.says": "Gifty dice",
    "trail.gifty.resist": "La clase resiste: todos muestran la Palma de Pausa y nombran la pista.",
    "trail.gifty.how": "Cómo resistir",
    "trail.gifty.resisted": "¡Resistimos! Lanza la moneda de Gifty",
    "trail.coin.star": "Lado de la estrella: ¡Gifty está vencido! A celebrar.",
    "trail.coin.beaten": "Gifty dice: {t}",
    "trail.coin.hook": "Lado del anzuelo: un Resbalón de Brillantina. Aunque todos hagan todo bien, un truco ingenioso a veces se cuela. Eso es verdad en la vida real y nunca es culpa de nadie.",
    "trail.slip.free": "El primer Resbalón de Brillantina es gratis. Sin Desvío.",
    "trail.slip.blocked": "El Candado de Latch bloquea el resbalón. Sin pompón y sin Desvío.",
    "trail.slip.undone": "El Cinturón de Herramientas de Fixit deshace el Desvío.",
    "trail.slip.detour": "La Tripulación resbala {n} espacios hacia atrás (un Desvío). Entra un pompón al Frasco de Brillantina.",
    "trail.slip.jar": "Entra un pompón al Frasco de Brillantina.",
    "trail.cancel": "Gastar una Ficha de Peldaño y decir una frase de Cuenta para cancelar el Desvío",
    "trail.cancelled": "La clase se lo contó a alguien y la brillantina se barrió. La Tripulación vuelve a donde estaba.",
    "trail.storm": "¡Tormenta de Chispas!",
    "trail.storm.b": "El frasco se desborda en una ventisca graciosa de brillantina. Todos se ponen de pie y hacen manos de jazz. Luego cada equipo dice una frase de la Escalera de Ayuda: contarle a un amigo, contarle a un adulto de confianza o denunciar. La ficha no retrocede. La clase gana un Listón de Rescate.",
    "trail.storm.done": "Dijimos nuestras frases",
    "trail.sunrise": "Docente: Viento del Amanecer",
    "trail.sunrise.help": "Empuja a la Tripulación hacia la Cima si falta tiempo.",
    "trail.sunrise.done": "¡Un viento amable sube a la Tripulación por el Camino de la Cima!",
    "trail.sunrise.no": "La Tripulación ya está cerca de la Cima.",
    "trail.end.h": "¡Cima Hackles!",
    "trail.end.sub": "La clase llegó a la cima junta.",
    "trail.tier.gold": "Cima de Oro",
    "trail.tier.silver": "Cima de Plata",
    "trail.tier.bronze": "Cima de Bronce",
    "trail.tier.b.gold": "Sin Tormentas de Chispas.",
    "trail.tier.b.silver": "Una Tormenta de Chispas.",
    "trail.tier.b.bronze": "Dos o más Tormentas de Chispas.",
    "trail.tier.note": "Todos los niveles reciben la misma ovación. Un Listón de Rescate significa que subieron la Escalera. Esa es justo la idea. El nivel muestra sobre todo cómo cayó la moneda, así que nadie recibe elogios ni regaños por él.",
    "trail.bigpause": "La Gran Pausa",
    "trail.bigpause.b": "Todos hacen Piel erizada, luego la Palma de Pausa con una respiración lenta, luego Ojos que Revisan y luego la Mano que Cuenta. Cada equipo dice algo que va a recordar.",
    "trail.gifty.final": "Gifty dice: “Bueno, bueno, ganaron. Pero quiero que conste que mi regalo era muy brillante.”",
    "trail.again": "Caminar otra vez",
    "trail.lab": "Volver al inicio del Laboratorio",
    "trail.live.event": "Turno {n}. Equipo {team}. {t}",
    "trail.live.result": "{c}. La Tripulación avanza {n} espacios hasta el espacio {p}.",
    "trail.live.slip": "Resbalón de Brillantina. Frasco {j} de 2.",
    "trail.live.beaten": "Gifty está vencido."
  }
});
