/* Secret Code Lab: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "secret.title": "Secret Code Lab",
    "secret.kicker": "Plate 3 of 6",
    "secret.lead": "Be a code maker and a code breaker. Turn the wheel, scramble a message, then crack some codes. This is a puzzle and a toy. Real encryption uses far bigger keys.",
    "secret.vocab": "Words to know",
    "secret.v.cipher": "Cipher: the recipe for scrambling.",
    "secret.v.key": "Key: the secret that unlocks it, like how far you turn the wheel.",
    "secret.v.plain": "Plaintext is the message before scrambling. Ciphertext is the scramble.",
    "secret.tab.wheel": "Shift wheel",
    "secret.tab.mixed": "Mixed alphabet",
    "secret.tab.crack": "Crack it",
    "secret.wheel.h": "The shift wheel",
    "secret.wheel.b": "The outer ring is the real message. The inner ring is the scramble. Turn the inner ring to set the key. For key 3, the inner D sits under the outer A.",
    "secret.key": "Key: {n}",
    "secret.keyLabel": "Key (how far to turn)",
    "secret.left": "Turn left",
    "secret.right": "Turn right",
    "secret.mode": "What do you want to do?",
    "secret.mode.enc": "Encode (message to scramble)",
    "secret.mode.dec": "Decode (scramble to message)",
    "secret.msg": "Pick a message",
    "secret.msgOr": "Or build one from words",
    "secret.clear": "Clear my words",
    "secret.built": "My words: {t}",
    "secret.builtNone": "No words picked yet.",
    "secret.in": "You start with",
    "secret.out": "You get",
    "secret.map": "Letter map for key {n}",
    "secret.mapSub": "Each letter in the top row becomes the letter under it.",
    "secret.mapPlain": "Message letter",
    "secret.mapCode": "Code letter",
    "secret.wheelAlt": "A cipher wheel. Outer ring A to Z. Inner ring turned by {n} places.",
    "secret.outer": "message",
    "secret.inner": "code",
    "secret.tiny": "A shift cipher has only 25 keys. A computer can try all 25 in a blink. That is why real encryption needs keys with more possibilities than there are grains of sand on every beach.",

    "secret.mixed.h": "The mixed-alphabet cipher",
    "secret.mixed.b": "Instead of shifting, every letter is swapped for a different letter in a scrambled alphabet. The scrambled alphabet is the key. There are far more possible keys than the 25 of the wheel.",
    "secret.mixed.guide": "Use the classroom key",
    "secret.mixed.own": "Make my own key",
    "secret.mixed.keyRow": "Key table",
    "secret.mixed.share": "A code only works if the key stays secret. Hand over the key in person, never in the same note as the code.",
    "secret.mixed.count": "Possible keys: about 403 septillion. Even trying 10 billion keys every second would take over a billion years.",

    "secret.crack.h": "Crack it",
    "secret.crack.b": "Solve the codes in any order. There is no timer. Each one is a puzzle, not a way to hack anyone.",
    "secret.puzzle": "Code {n} of {total}",
    "secret.solved": "Solved",
    "secret.todo": "Not yet",
    "secret.cipherIs": "The scrambled message",
    "secret.hintKey": "Hint: the key is {k}.",
    "secret.tries": "Keys you have tried: {n}",
    "secret.try.shift": "Turn the wheel until words appear. Then press the button.",
    "secret.read": "That reads right!",
    "secret.checking": "Your message so far",
    "secret.good": "Code cracked! The message says: {m}",
    "secret.again": "Not quite yet. Keep turning. There are only 25 keys.",
    "secret.again.mixed": "Not quite yet. Fill every code letter, then check again.",
    "secret.keyShown": "The key is shown below. Find each code letter in the bottom row and write the letter above it.",
    "secret.keyHidden": "No key this time. Use the letter counts and the hint button. In English, E and T show up a lot.",
    "secret.keyHiddenEs": "No key this time. Use the letter counts and the hint button. In Spanish, E and A show up a lot.",
    "secret.assign": "Code letter {c} means",
    "secret.blank": "(not sure)",
    "secret.hintBtn": "Show me one letter",
    "secret.hintUsed": "Letters revealed: {n}",
    "secret.freq": "Letter counts in the code",
    "secret.brute": "All 25 keys tried at once",
    "secret.bruteSub": "A computer does this instantly. One row makes words.",
    "secret.allDone": "All the codes are cracked. You are a Code Breaker.",
    "secret.badge": "Code Breaker",
    "secret.next": "Next code",
    "secret.safety": "Remember: a secret key is only safe while it stays secret. If someone asks you for your keys or passwords, Pause, Check, Tell.",
    "secret.lab": "Back to Lab home",
    "secret.live.key": "Key {n}.",
    "secret.live.out": "Result: {t}"
  },
  es: {
    "secret.title": "Laboratorio de Códigos Secretos",
    "secret.kicker": "Lámina 3 de 6",
    "secret.lead": "Sé creador y descifrador de códigos. Gira la rueda, revuelve un mensaje y luego resuelve códigos. Es un rompecabezas y un juguete. El cifrado de verdad usa claves mucho más grandes.",
    "secret.vocab": "Palabras para conocer",
    "secret.v.cipher": "Cifrado: la receta para revolver.",
    "secret.v.key": "Clave: el secreto que lo abre, como cuánto giras la rueda.",
    "secret.v.plain": "El texto claro es el mensaje antes de revolverlo. El texto cifrado es el revoltijo.",
    "secret.tab.wheel": "Rueda de desplazamiento",
    "secret.tab.mixed": "Alfabeto mixto",
    "secret.tab.crack": "Descífralo",
    "secret.wheel.h": "La rueda de desplazamiento",
    "secret.wheel.b": "El anillo de afuera es el mensaje de verdad. El anillo de adentro es el revoltijo. Gira el anillo de adentro para poner la clave. Con la clave 3, la D de adentro queda debajo de la A de afuera.",
    "secret.key": "Clave: {n}",
    "secret.keyLabel": "Clave (cuánto girar)",
    "secret.left": "Girar a la izquierda",
    "secret.right": "Girar a la derecha",
    "secret.mode": "¿Qué quieres hacer?",
    "secret.mode.enc": "Cifrar (mensaje a revoltijo)",
    "secret.mode.dec": "Descifrar (revoltijo a mensaje)",
    "secret.msg": "Elige un mensaje",
    "secret.msgOr": "O arma uno con palabras",
    "secret.clear": "Borrar mis palabras",
    "secret.built": "Mis palabras: {t}",
    "secret.builtNone": "Todavía no elegiste palabras.",
    "secret.in": "Empiezas con",
    "secret.out": "Obtienes",
    "secret.map": "Mapa de letras para la clave {n}",
    "secret.mapSub": "Cada letra de la fila de arriba se convierte en la letra de abajo.",
    "secret.mapPlain": "Letra del mensaje",
    "secret.mapCode": "Letra del código",
    "secret.wheelAlt": "Una rueda de cifrado. Anillo de afuera de la A a la Z. Anillo de adentro girado {n} lugares.",
    "secret.outer": "mensaje",
    "secret.inner": "código",
    "secret.tiny": "Un cifrado de desplazamiento tiene solo 25 claves. Una computadora puede probar las 25 en un parpadeo. Por eso el cifrado de verdad necesita claves con más posibilidades que granos de arena en todas las playas.",

    "secret.mixed.h": "El cifrado de alfabeto mixto",
    "secret.mixed.b": "En vez de desplazar, cada letra se cambia por otra de un alfabeto revuelto. El alfabeto revuelto es la clave. Hay muchísimas más claves posibles que las 25 de la rueda.",
    "secret.mixed.guide": "Usar la clave de la clase",
    "secret.mixed.own": "Hacer mi propia clave",
    "secret.mixed.keyRow": "Tabla de la clave",
    "secret.mixed.share": "Un código solo funciona si la clave sigue en secreto. Entrega la clave en persona, nunca en la misma nota que el código.",
    "secret.mixed.count": "Claves posibles: unos 403 cuatrillones. Incluso probando 10 mil millones de claves por segundo, tardarías más de mil millones de años.",

    "secret.crack.h": "Descífralo",
    "secret.crack.b": "Resuelve los códigos en el orden que quieras. No hay temporizador. Cada uno es un rompecabezas, no una forma de hackear a nadie.",
    "secret.puzzle": "Código {n} de {total}",
    "secret.solved": "Resuelto",
    "secret.todo": "Todavía no",
    "secret.cipherIs": "El mensaje revuelto",
    "secret.hintKey": "Pista: la clave es {k}.",
    "secret.tries": "Claves que has probado: {n}",
    "secret.try.shift": "Gira la rueda hasta que aparezcan palabras. Luego pulsa el botón.",
    "secret.read": "¡Eso se lee bien!",
    "secret.checking": "Tu mensaje hasta ahora",
    "secret.good": "¡Código descifrado! El mensaje dice: {m}",
    "secret.again": "Todavía no. Sigue girando. Solo hay 25 claves.",
    "secret.again.mixed": "Todavía no. Llena todas las letras del código y revisa otra vez.",
    "secret.keyShown": "La clave se muestra abajo. Busca cada letra del código en la fila de abajo y anota la letra de arriba.",
    "secret.keyHidden": "Esta vez no hay clave. Usa el conteo de letras y el botón de pista. En español, la E y la A aparecen mucho.",
    "secret.keyHiddenEs": "Esta vez no hay clave. Usa el conteo de letras y el botón de pista. En español, la E y la A aparecen mucho.",
    "secret.assign": "La letra del código {c} significa",
    "secret.blank": "(no estoy seguro)",
    "secret.hintBtn": "Muéstrame una letra",
    "secret.hintUsed": "Letras reveladas: {n}",
    "secret.freq": "Conteo de letras en el código",
    "secret.brute": "Las 25 claves probadas a la vez",
    "secret.bruteSub": "Una computadora hace esto al instante. Una fila forma palabras.",
    "secret.allDone": "Descifraste todos los códigos. Eres Descifrador de Códigos.",
    "secret.badge": "Descifrador de Códigos",
    "secret.next": "Siguiente código",
    "secret.safety": "Recuerda: una clave secreta solo está segura mientras siga en secreto. Si alguien te pide tus claves o contraseñas, Pausa, Revisa, Cuenta.",
    "secret.lab": "Volver al inicio del Laboratorio",
    "secret.live.key": "Clave {n}.",
    "secret.live.out": "Resultado: {t}"
  }
});
