/* Passphrase Lab: on-screen text. Spanish is a DRAFT for native-speaker review. */
HK.register({
  en: {
    "pp.title": "Passphrase Lab",
    "pp.kicker": "Plate 2 of 6",
    "pp.lead": "Build two practice secrets out of dice rolls and see how many guesses each one could take. The numbers show why long and random wins.",
    "pp.never.h": "Never type a real password here",
    "pp.never.b": "There is nowhere to type. You build practice secrets with dice rolls and word pickers. A practice secret is only for learning. Nothing you do here leaves this page.",
    "pp.assume.h": "Teaching assumptions",
    "pp.assume.b": "Classroom model: 1,000 guesses per second, a gentle number for class. Attacker model: 10 billion guesses per second against a stolen file that was scrambled with a fast method. That second number is a teaching assumption and not a measurement. Real speeds change with the computer and the scrambling method.",
    "pp.secret": "Secret {x}",
    "pp.kind": "What is it made of?",
    "pp.kind.cw": "Dice words from the classroom list (36 words)",
    "pp.kind.rw": "Dice words from a real list (7,776 words)",
    "pp.kind.ch": "Random characters",
    "pp.count.words": "Number of words",
    "pp.count.chars": "Number of characters",
    "pp.alpha": "Which characters?",
    "pp.alpha.digits": "Digits only (10)",
    "pp.alpha.lower": "Lowercase letters (26)",
    "pp.alpha.mixed": "Lowercase and uppercase letters (52)",
    "pp.alpha.alnum": "Letters and digits (62)",
    "pp.alpha.keyboard": "Full keyboard (94)",
    "pp.roll": "Roll the dice",
    "pp.rollAgain": "Roll again",
    "pp.practiceOnly": "Practice only. Never use a practice secret for a real account.",
    "pp.dice.cw": "Two dice pick one word: the first die is the row and the second die is the column.",
    "pp.dice.rw": "In a real list, five dice point to one word. This page shows the dice and leaves the 7,776 words in the book.",
    "pp.sample": "Pretend sample (never use it)",
    "pp.word": "Word {n}",
    "pp.pickNote": "You can also pick words yourself. Words you pick are easier to guess than dice words, so the numbers below are the best case.",
    "pp.die": "die showing {n}",
    "pp.wordDice": "Word {n}: dice {d}",

    "pp.compare": "Compare the two secrets",
    "pp.row.possible": "Possible secrets",
    "pp.row.words": "In words",
    "pp.row.bits": "Bits (each bit doubles the work)",
    "pp.row.classAvg": "Classroom model, average time",
    "pp.row.classAll": "Classroom model, longest time",
    "pp.row.attAvg": "Attacker model, average time",
    "pp.row.attAll": "Attacker model, longest time",
    "pp.avgHelp": "Average time means finding it after trying about half of the possibilities. Longest time means trying every one.",
    "pp.about": "about {n}",
    "pp.bar": "Strength by bits: bigger bar, harder to guess",
    "pp.summary": "Secret {x}: {desc}. {n} possible secrets. Attacker model, average: {t}.",
    "pp.desc.words": "{n} dice words from a list of {l}",
    "pp.desc.chars": "{n} random characters from a set of {l}",
    "pp.vs.more": "Secret {a} has about {r} times more possibilities than Secret {b}.",
    "pp.vs.same": "Both secrets have about the same number of possibilities.",
    "pp.vs.huge": "Secret {a} has about 10^{e} times more possibilities than Secret {b}.",
    "pp.universe": "That is about {x} times the age of the universe.",
    "pp.universe.less": "The age of the universe is about 13.8 billion years. This time is shorter than that.",

    "pp.t.instant": "less than a thousandth of a second",
    "pp.t.milliseconds": "about {n} milliseconds",
    "pp.t.seconds": "about {n} seconds",
    "pp.t.seconds.one": "about 1 second",
    "pp.t.minutes": "about {n} minutes",
    "pp.t.minutes.one": "about 1 minute",
    "pp.t.hours": "about {n} hours",
    "pp.t.hours.one": "about 1 hour",
    "pp.t.days": "about {n} days",
    "pp.t.days.one": "about 1 day",
    "pp.t.years": "about {n} years",
    "pp.t.years.one": "about 1 year",
    "pp.t.sci": "about {m} x 10^{e} years",
    "pp.scale.million": "million",
    "pp.scale.billion": "billion",
    "pp.scale.trillion": "trillion",
    "pp.scale.quadrillion": "quadrillion",
    "pp.scale.quintillion": "quintillion",
    "pp.scale.sextillion": "sextillion",
    "pp.scale.septillion": "septillion",

    "pp.table.honest": "The honest table",
    "pp.table.honestSub": "Average time at 10 billion guesses per second (attacker model, a teaching assumption). Press Try it to load a row into Secret A.",
    "pp.table.class": "The classroom list table",
    "pp.table.classSub": "Our 36-word list at 1,000 guesses per second (classroom model). Each new word makes the lock 36 times bigger.",
    "pp.th.secret": "Secret",
    "pp.th.possible": "Possible secrets",
    "pp.th.avg": "Average time",
    "pp.th.all": "Longest time",
    "pp.th.try": "Try it",
    "pp.try": "Try it",
    "pp.tryLabel": "Try {s} as Secret A",
    "pp.rowLabel.words": "{n} random words (list of {l})",
    "pp.rowLabel.chars": "{n} random characters (set of {l})",
    "pp.read": "Read the table honestly: 3 words is weak, 4 is borderline for important accounts, and 5 to 6 is strong for a password you must memorize. Random and long is the lesson. Words are not better than symbols just for being words.",

    "pp.vault": "Dice Vault",
    "pp.vault.b": "Each extra die multiplies the guessing by 6. Slide to add dice.",
    "pp.vault.n": "Dice in the secret: {n}",
    "pp.vault.out": "{n} dice: {c} possibilities. Classroom model, longest time: {t}.",

    "pp.real.h": "What really breaks into accounts",
    "pp.real.b": "Most stolen accounts are not cracked at all. They come from reusing one password on many sites, from tricks that make people hand it over, and from bad software. A strong, different password for each account helps against all three. A password manager can remember long random ones so you do not have to.",
    "pp.online.h": "Online and offline guessing",
    "pp.online.b": "A website can slow guessers down or lock the account after a few tries. After a company is hacked, an attacker may hold a stolen file of scrambled passwords and guess on their own computers with no lockout. Long random passphrases are built for that second case.",
    "pp.human.h": "Only dice count",
    "pp.human.b": "These numbers only hold when the words are picked by dice. A phrase a person invents, a quote, a pet name or a favorite team is much easier to guess than its length suggests. Swapping a for @ barely helps. Guessing tools try those swaps first.",
    "pp.toy": "The classroom list has only 36 words. It is a toy so a whole class can see the idea on one page. A real list has 7,776 words.",
    "pp.tell": "If someone ever learns your password, it is never your fault. Change it, tell a trusted adult, and fix it together.",
    "pp.again": "Roll again",
    "pp.lab": "Back to Lab home",
    "pp.live.changed": "Secret {x} updated. {s}",
    "pp.live.roll": "Secret {x} rolled."
  },
  es: {
    "pp.title": "Laboratorio de Frases de Contraseña",
    "pp.kicker": "Lámina 2 de 6",
    "pp.lead": "Arma dos secretos de práctica con tiradas de dados y mira cuántos intentos podría necesitar cada uno. Los números muestran por qué gana lo largo y al azar.",
    "pp.never.h": "Nunca escribas una contraseña real aquí",
    "pp.never.b": "No hay dónde escribir. Armas secretos de práctica con tiradas de dados y selectores de palabras. Un secreto de práctica es solo para aprender. Nada de lo que haces aquí sale de esta página.",
    "pp.assume.h": "Supuestos para enseñar",
    "pp.assume.b": "Modelo de clase: 1,000 intentos por segundo, un número suave para el aula. Modelo de atacante: 10 mil millones de intentos por segundo contra un archivo robado que se revolvió con un método rápido. Ese segundo número es un supuesto para enseñar y no una medición. Las velocidades reales cambian con la computadora y con el método de revolver.",
    "pp.secret": "Secreto {x}",
    "pp.kind": "¿De qué está hecho?",
    "pp.kind.cw": "Palabras con dados de la lista de la clase (36 palabras)",
    "pp.kind.rw": "Palabras con dados de una lista real (7,776 palabras)",
    "pp.kind.ch": "Caracteres al azar",
    "pp.count.words": "Cantidad de palabras",
    "pp.count.chars": "Cantidad de caracteres",
    "pp.alpha": "¿Qué caracteres?",
    "pp.alpha.digits": "Solo dígitos (10)",
    "pp.alpha.lower": "Letras minúsculas (26)",
    "pp.alpha.mixed": "Letras minúsculas y mayúsculas (52)",
    "pp.alpha.alnum": "Letras y dígitos (62)",
    "pp.alpha.keyboard": "Todo el teclado (94)",
    "pp.roll": "Tirar los dados",
    "pp.rollAgain": "Tirar otra vez",
    "pp.practiceOnly": "Solo es práctica. Nunca uses un secreto de práctica en una cuenta real.",
    "pp.dice.cw": "Dos dados eligen una palabra: el primer dado es la fila y el segundo dado es la columna.",
    "pp.dice.rw": "En una lista real, cinco dados señalan una palabra. Esta página muestra los dados y deja las 7,776 palabras en el libro.",
    "pp.sample": "Ejemplo de mentira (nunca lo uses)",
    "pp.word": "Palabra {n}",
    "pp.pickNote": "También puedes elegir las palabras tú. Las palabras que eliges son más fáciles de adivinar que las de los dados, así que los números de abajo son el mejor caso.",
    "pp.die": "dado que muestra {n}",
    "pp.wordDice": "Palabra {n}: dados {d}",

    "pp.compare": "Compara los dos secretos",
    "pp.row.possible": "Secretos posibles",
    "pp.row.words": "En palabras",
    "pp.row.bits": "Bits (cada bit duplica el trabajo)",
    "pp.row.classAvg": "Modelo de clase, tiempo promedio",
    "pp.row.classAll": "Modelo de clase, tiempo máximo",
    "pp.row.attAvg": "Modelo de atacante, tiempo promedio",
    "pp.row.attAll": "Modelo de atacante, tiempo máximo",
    "pp.avgHelp": "El tiempo promedio es encontrarlo después de probar más o menos la mitad de las posibilidades. El tiempo máximo es probarlas todas.",
    "pp.about": "unos {n}",
    "pp.bar": "Fuerza en bits: barra más grande, más difícil de adivinar",
    "pp.summary": "Secreto {x}: {desc}. {n} secretos posibles. Modelo de atacante, promedio: {t}.",
    "pp.desc.words": "{n} palabras con dados de una lista de {l}",
    "pp.desc.chars": "{n} caracteres al azar de un conjunto de {l}",
    "pp.vs.more": "El Secreto {a} tiene unas {r} veces más posibilidades que el Secreto {b}.",
    "pp.vs.same": "Los dos secretos tienen más o menos la misma cantidad de posibilidades.",
    "pp.vs.huge": "El Secreto {a} tiene unas 10^{e} veces más posibilidades que el Secreto {b}.",
    "pp.universe": "Eso es unas {x} veces la edad del universo.",
    "pp.universe.less": "La edad del universo es de unos 13.8 mil millones de años. Este tiempo es menor.",

    "pp.t.instant": "menos de una milésima de segundo",
    "pp.t.milliseconds": "unos {n} milisegundos",
    "pp.t.seconds": "unos {n} segundos",
    "pp.t.seconds.one": "1 segundo",
    "pp.t.minutes": "unos {n} minutos",
    "pp.t.minutes.one": "1 minuto",
    "pp.t.hours": "unas {n} horas",
    "pp.t.hours.one": "1 hora",
    "pp.t.days": "unos {n} días",
    "pp.t.days.one": "1 día",
    "pp.t.years": "unos {n} años",
    "pp.t.years.one": "1 año",
    "pp.t.sci": "unos {m} x 10^{e} años",
    "pp.scale.million": "millones",
    "pp.scale.billion": "mil millones",
    "pp.scale.trillion": "billones",
    "pp.scale.quadrillion": "mil billones",
    "pp.scale.quintillion": "trillones",
    "pp.scale.sextillion": "mil trillones",
    "pp.scale.septillion": "cuatrillones",

    "pp.table.honest": "La tabla honesta",
    "pp.table.honestSub": "Tiempo promedio a 10 mil millones de intentos por segundo (modelo de atacante, un supuesto para enseñar). Pulsa Probar para cargar una fila en el Secreto A.",
    "pp.table.class": "La tabla de la lista de la clase",
    "pp.table.classSub": "Nuestra lista de 36 palabras a 1,000 intentos por segundo (modelo de clase). Cada palabra nueva hace el candado 36 veces más grande.",
    "pp.th.secret": "Secreto",
    "pp.th.possible": "Secretos posibles",
    "pp.th.avg": "Tiempo promedio",
    "pp.th.all": "Tiempo máximo",
    "pp.th.try": "Probar",
    "pp.try": "Probar",
    "pp.tryLabel": "Probar {s} como Secreto A",
    "pp.rowLabel.words": "{n} palabras al azar (lista de {l})",
    "pp.rowLabel.chars": "{n} caracteres al azar (conjunto de {l})",
    "pp.read": "Lee la tabla con honestidad: 3 palabras es poco, 4 es justo para cuentas importantes y de 5 a 6 es fuerte para una contraseña que debes memorizar. Al azar y largo es la lección. Las palabras no son mejores que los símbolos por ser palabras.",

    "pp.vault": "Bóveda de Dados",
    "pp.vault.b": "Cada dado extra multiplica por 6 los intentos. Desliza para añadir dados.",
    "pp.vault.n": "Dados en el secreto: {n}",
    "pp.vault.out": "{n} dados: {c} posibilidades. Modelo de clase, tiempo máximo: {t}.",

    "pp.real.h": "Lo que de verdad rompe las cuentas",
    "pp.real.b": "La mayoría de las cuentas robadas no se descifran. Vienen de usar una misma contraseña en muchos sitios, de trucos que hacen que la gente la entregue y de programas dañinos. Una contraseña fuerte y distinta para cada cuenta ayuda con las tres cosas. Un administrador de contraseñas puede recordar las largas y al azar para que tú no tengas que hacerlo.",
    "pp.online.h": "Intentos en línea y sin conexión",
    "pp.online.b": "Un sitio web puede frenar a quien adivina o bloquear la cuenta después de pocos intentos. Cuando hackean a una empresa, un atacante puede tener un archivo robado de contraseñas revueltas y adivinar en sus propias computadoras sin bloqueo. Las frases largas y al azar están hechas para ese segundo caso.",
    "pp.human.h": "Solo cuentan los dados",
    "pp.human.b": "Estos números solo valen cuando las palabras las eligen los dados. Una frase inventada por una persona, una cita, el nombre de una mascota o un equipo favorito es mucho más fácil de adivinar de lo que sugiere su largo. Cambiar a por @ casi no ayuda. Las herramientas de adivinar prueban esos cambios primero.",
    "pp.toy": "La lista de la clase tiene solo 36 palabras. Es de juguete para que toda la clase vea la idea en una página. Una lista real tiene 7,776 palabras.",
    "pp.tell": "Si alguien llega a saber tu contraseña, nunca es tu culpa. Cámbiala, cuéntaselo a un adulto de confianza y arréglenlo juntos.",
    "pp.again": "Tirar otra vez",
    "pp.lab": "Volver al inicio del Laboratorio",
    "pp.live.changed": "Secreto {x} actualizado. {s}",
    "pp.live.roll": "Secreto {x} tirado."
  }
});

/* The 6x6 word lists (row = first die, column = second die). English list: 3-5 Reproducibles R-2.1.
   Spanish list: draft, no accents or enye so it prints the same way as the English sheet. */
window.PP_WORDS = {
  en: ["apple","bridge","cloud","drum","eagle","forest",
       "garden","harbor","island","jungle","kite","lantern",
       "meadow","nickel","orbit","pepper","quilt","river",
       "saddle","tunnel","umbrella","violin","walnut","yarn",
       "zebra","anchor","button","candle","dragon","engine",
       "feather","glacier","hammock","igloo","jigsaw","kettle"],
  es: ["manzana","puente","nube","tambor","aguila","bosque",
       "jardin","puerto","isla","selva","cometa","farol",
       "prado","moneda","orbita","pimienta","manta","rio",
       "silla","tunel","paraguas","violin","nuez","hilo",
       "cebra","ancla","boton","vela","dragon","motor",
       "pluma","glaciar","hamaca","iglu","puzle","tetera"]
};
